/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GiftMetadata } from './GiftMetadata';
import type { ListOfGiftItemDto } from './ListOfGiftItemDto';
import type { TebexAdminOrderDetailDto } from './TebexAdminOrderDetailDto';
import type { TebexRecipientSnapshot } from './TebexRecipientSnapshot';

/**
 * Admin-facing detailed order view.
 */
export interface AdminOrderDetailDto {
	orderId: string;
	buyerId: string;
	/** @nullable */
	recipientId?: string | null;
	/** @nullable */
	recipientGuildId?: string | null;
	status: string;
	provider: string;
	/** @nullable */
	transactionId?: string | null;
	/** @nullable */
	basketIdent?: string | null;
	/** @nullable */
	recurringReference?: string | null;
	/** @nullable */
	providerStatus?: string | null;
	/** @nullable */
	purchaseMode?: string | null;
	/** @nullable */
	recipientResolutionStatus?: string | null;
	totalPrice: number;
	currency: string;
	orderDate: string;
	/** @nullable */
	completedAt?: string | null;
	/** @nullable */
	refundedAt?: string | null;
	/** @nullable */
	disputedAt?: string | null;
	recipientSnapshot?: TebexRecipientSnapshot | null;
	giftMetadata?: GiftMetadata | null;
	tebex?: TebexAdminOrderDetailDto | null;
	items: ListOfGiftItemDto;
}
