/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AdminOrderDetailDtoRecipientSnapshot } from './AdminOrderDetailDtoRecipientSnapshot';
import type { AdminOrderDetailDtoGiftMetadata } from './AdminOrderDetailDtoGiftMetadata';
import type { AdminOrderDetailDtoTebex } from './AdminOrderDetailDtoTebex';
import type { GiftItemDto } from './GiftItemDto';

/**
 * Admin-facing detailed order view.
 */
export interface AdminOrderDetailDto {
	orderId: string;
	buyerId: string;
	/** @nullable */
	recipientId?: string | null;
	/** @nullable */
	recipientGuildId?: string | null;
	status: string;
	provider: string;
	/** @nullable */
	transactionId?: string | null;
	/** @nullable */
	basketIdent?: string | null;
	/** @nullable */
	recurringReference?: string | null;
	/** @nullable */
	providerStatus?: string | null;
	/** @nullable */
	purchaseMode?: string | null;
	/** @nullable */
	recipientResolutionStatus?: string | null;
	totalPrice: number;
	currency: string;
	orderDate: string;
	/** @nullable */
	completedAt?: string | null;
	/** @nullable */
	refundedAt?: string | null;
	/** @nullable */
	disputedAt?: string | null;
	/** @nullable */
	recipientSnapshot?: AdminOrderDetailDtoRecipientSnapshot;
	/** @nullable */
	giftMetadata?: AdminOrderDetailDtoGiftMetadata;
	/** @nullable */
	tebex?: AdminOrderDetailDtoTebex;
	items: GiftItemDto[];
}
