/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { AuthorDto } from './AuthorDto';
import type { GuideAuthorDto } from './GuideAuthorDto';

export interface AdminDraftGuideDto {
	id: number;
	slug: string;
	title: string;
	description: string;
	type: string;
	status: string;
	createdAt: string;
	lastUpdatedAt: string;
	revisionNumber: number;
	author: AuthorDto;
	authors: GuideAuthorDto[];
	tags: string[];
	tagIds: number[];
}
