/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EventMemberStatus } from './EventMemberStatus';
import type { AdminEventMemberDtoData } from './AdminEventMemberDtoData';
import type { AdminEventMemberDtoMeta } from './AdminEventMemberDtoMeta';

export interface AdminEventMemberDto {
	/** @nullable */
	playerUuid?: string | null;
	/** @nullable */
	profileId?: string | null;
	/** @nullable */
	playerName?: string | null;
	eventId: string;
	/** @nullable */
	teamId?: string | null;
	status: EventMemberStatus;
	/** @nullable */
	score?: string | null;
	/** @nullable */
	lastUpdated?: string | null;
	/** @nullable */
	disqualified?: boolean | null;
	/** @nullable */
	data?: AdminEventMemberDtoData;
	/** @nullable */
	estimatedTimeActive?: string | null;
	/**
	 * Metadata of the entry
	 * @nullable
	 */
	meta?: AdminEventMemberDtoMeta;
	id: number;
	/** @nullable */
	accountId?: string | null;
	/**
	 * @maxLength 128
	 * @nullable
	 */
	notes?: string | null;
}
