/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AnnouncementType } from './AnnouncementType';

export interface AnnouncementDto {
	/** Announcement title */
	title: string;
	/** Announcement content */
	content: string;
	/** Type of the announcement */
	type: AnnouncementType;
	/**
	 * Label for the target of the announcement (e.g. "Read more", "View article")
	 * @nullable
	 */
	targetLabel?: string | null;
	/**
	 * Url to read more about the announcement
	 * @nullable
	 */
	targetUrl?: string | null;
	/**
	 * Optional time stamp for when the topic of the announcement starts
	 * @nullable
	 */
	targetStartsAt?: string | null;
	/**
	 * Optional time stamp for when the topic of the announcement ends
	 * @nullable
	 */
	targetEndsAt?: string | null;
	/** Announcement creation date */
	createdAt: string;
	/** Announcement expiration date (will no longer be shown after this date) */
	expiresAt: string;
	/** Announcement id */
	id: string;
}
