/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type AnnouncementType = (typeof AnnouncementType)[keyof typeof AnnouncementType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnnouncementType = {
	other: 'other',
	update: 'update',
	article: 'article',
	news: 'news',
	event: 'event',
	maintenance: 'maintenance',
	shop: 'shop',
} as const;
