/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuctionItemVariation } from './AuctionItemVariation';

export interface AuctionItemDto {
	skyblockId: string;
	variantKey: string;
	/** Data used to generate variant key (easier to parse) */
	variedBy: AuctionItemVariation;
	/** Lowest price seen recently (excluding outliers) */
	lowest: number;
	/** Volume of prices used to get the lowest recent price */
	lowestVolume: number;
	/** Lowest price seen in 3 days (excluding outliers) */
	lowest3Day: number;
	/** Volume of prices used to get the lowest 3 day price */
	lowest3DayVolume: number;
	/** Lowest price seen in 7 days (excluding outliers) */
	lowest7Day: number;
	/** Volume of prices ued to get lowest 3 day price */
	lowest7DayVolume: number;
}
