/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuctionItemVariation } from './AuctionItemVariation';

export interface AuctionItemDto {
	skyblockId: string;
	variantKey: string;
	variedBy: AuctionItemVariation;
	/** Lowest price seen recently (excluding outliers) */
	lowest: number;
	/** Volume of prices used to get the lowest recent price */
	lowestVolume: number;
	/** Lowest price seen in 3 days (excluding outliers) */
	lowest3Day: number;
	/** Volume of prices used to get the lowest 3 day price */
	lowest3DayVolume: number;
	/** Lowest price seen in 7 days (excluding outliers) */
	lowest7Day: number;
	/** Volume of prices ued to get lowest 3 day price */
	lowest7DayVolume: number;
	/** Last known valid lowest price - persists up to a year after item stops being auctioned */
	last: number;
	/** Absolute cheapest current BIN listing (no outlier filtering) */
	rawLowest: number;
	calculatedAt: string;
	/** @nullable */
	lowestObservedAt?: string | null;
	/** @nullable */
	lastLowestAt?: string | null;
}
