/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuthResponseDtoPendingConfirmation } from './AuthResponseDtoPendingConfirmation';

export interface AuthResponseDto {
	/** Access token for the user */
	access_token: string;
	/**
	 * Expiry date of the access token in Unix timestamp seconds
	 * @nullable
	 */
	expires_in?: string | null;
	/** Refresh token for the user */
	refresh_token: string;
	/**
	 * The pending confirmation for the user, if any
	 * @nullable
	 */
	pending_confirmation?: AuthResponseDtoPendingConfirmation;
	/** If this is the user's first login */
	first_login: boolean;
}
