/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ConfirmationDto } from './ConfirmationDto';
import type { StringArray } from './StringArray';

export interface AuthSessionDto {
	/** Discord user ID */
	id: string;
	/** Discord username */
	username: string;
	/** Discord avatar hash */
	avatar: string;
	/** Primary Minecraft IGN */
	ign: string;
	/**
	 * Formatted Primary Minecraft IGN
	 * @nullable
	 */
	fIgn?: string | null;
	/** Primary Minecraft UUID */
	uuid: string;
	roles: StringArray;
	flags: StringArray;
	pending_confirmation?: ConfirmationDto | null;
}
