/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfEntitlementDto } from './ListOfEntitlementDto';
import type { ListOfMinecraftAccountDetailsDto } from './ListOfMinecraftAccountDetailsDto';
import type { ListOfString } from './ListOfString';
import type { ListOfWeightStyleLinkedDto } from './ListOfWeightStyleLinkedDto';
import type { UserSettingsDto } from './UserSettingsDto';

export interface AuthorizedAccountDto {
	/** Discord user ID */
	id: string;
	/** Discord display name */
	displayName: string;
	/** Discord username (unique) */
	username: string;
	/** @nullable */
	discriminator?: string | null;
	/**
	 * Discord user locale
	 * @nullable
	 */
	locale?: string | null;
	/**
	 * Discord avatar URL hash
	 * @nullable
	 */
	avatar?: string | null;
	/**
	 * Discord banner URL hash
	 * @nullable
	 */
	banner?: string | null;
	settings: UserSettingsDto;
	entitlements: ListOfEntitlementDto;
	cosmetics: ListOfWeightStyleLinkedDto;
	minecraftAccounts: ListOfMinecraftAccountDetailsDto;
	dismissedAnnouncements: ListOfString;
}
