/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { Badge } from './Badge';
import type { BadgeUnlockConditionConditions } from './BadgeUnlockConditionConditions';

export interface BadgeUnlockCondition {
	id: number;
	badgeId: number;
	badge: Badge;
	/**
	 * The event name that triggers evaluation of this condition, e.g. "guide.approved"
	 * @maxLength 150
	 */
	eventName: string;
	/**
	 * Optional JSONB column for advanced condition logic in the future
	 * @nullable
	 */
	conditions?: BadgeUnlockConditionConditions;
}
