/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { BazaarProductSummaryDtoOrders } from './BazaarProductSummaryDtoOrders';

export interface BazaarProductSummaryDto {
	/**
	 * Name of the item if it exists.
	 * @nullable
	 */
	name?: string | null;
	/** NPC sell price of the item if it exists. */
	npc: number;
	/** Instant Sell price taken directly from most recently fetched data */
	sell: number;
	/** Instant Buy price taken directly from most recently fetched data */
	buy: number;
	/** Sell Order price calculated from most recently fetched data */
	sellOrder: number;
	/** Buy Order price calculated from most recently fetched data */
	buyOrder: number;
	/** Top buy-order price from the current order book */
	topBuyOrder: number;
	/** Top sell-order price from the current order book */
	topSellOrder: number;
	/** Calculated average Instant Sell price that should be more resistant to price fluctuations */
	averageSell: number;
	/** Calculated average Instant Buy price that should be more resistant to price fluctuations */
	averageBuy: number;
	/** Calculated average Sell Order price that should be more resistant to price fluctuations */
	averageSellOrder: number;
	/** Calculated average top sell-order price */
	averageTopSellOrder: number;
	/** Calculated average Buy Order price that should be more resistant to price fluctuations */
	averageBuyOrder: number;
	/** Calculated average top buy-order price */
	averageTopBuyOrder: number;
	/**
	 * Current orders in the bazaar for this item if they exist.
	 * @nullable
	 */
	orders?: BazaarProductSummaryDtoOrders;
}
