/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndInt64 } from './DictionaryOfStringAndInt64';
import type { ListOfBestiaryTopMobDto } from './ListOfBestiaryTopMobDto';

/**
 * Derived bestiary aggregates (per-base-mob kill totals, top mobs, totals) computed from
 *             Bestiary. Hypixel exposes per-tier kill keys like "wolf_1", "wolf_2"; this
 *             summary collapses those into a single entry per base mob id.
 */
export interface BestiaryDerivationsDto {
	milestoneLevel: number;
	totalKills: bigint;
	totalDeaths: bigint;
	uniqueMobsTracked: number;
	killsByMob: DictionaryOfStringAndInt64;
	deathsByMob: DictionaryOfStringAndInt64;
	topMobs: ListOfBestiaryTopMobDto;
	/** @nullable */
	lastKilledMob?: string | null;
}
