/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type BugReportStatus = (typeof BugReportStatus)[keyof typeof BugReportStatus];

export const BugReportStatus = {
	new: 'new',
	investigating: 'investigating',
	needsInformation: 'needsInformation',
	resolved: 'resolved',
	closed: 'closed',
} as const;
