/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { TebexRecipientMode } from './TebexRecipientMode';

export interface CheckoutRecipientDto {
	mode?: TebexRecipientMode | null;
	/** @nullable */
	playerUuidOrIgn?: string | null;
	/** @nullable */
	guildId?: bigint | null;
	/** @nullable */
	message?: string | null;
}
