/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { CollectionRecapIncreases } from './CollectionRecapIncreases';
import type { CollectionRecapGlobalTotals } from './CollectionRecapGlobalTotals';
import type { CollectionRecapAverageComparison } from './CollectionRecapAverageComparison';
import type { MonthlyStatRecap } from './MonthlyStatRecap';

export interface CollectionRecap {
	increases: CollectionRecapIncreases;
	globalTotals: CollectionRecapGlobalTotals;
	averageComparison: CollectionRecapAverageComparison;
	monthly: MonthlyStatRecap[];
}
