/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { CollectionSummaryDtoBosses } from './CollectionSummaryDtoBosses';
import type { CollectionSummaryDtoKuudra } from './CollectionSummaryDtoKuudra';

/**
 * Derived summary describing tier progression for boss collections (Necron drops, etc.)
and Kuudra essence tier requirements.
 */
export interface CollectionSummaryDto {
	/** Per-boss collection tier progress, keyed by boss id (e.g. "necron"). */
	bosses: CollectionSummaryDtoBosses;
	/**
	 * Kuudra essence tier progression based on the player's KUUDRA collection amount.
	 * @nullable
	 */
	kuudra?: CollectionSummaryDtoKuudra;
}
