/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { CommunityUpgradeInProgressDto } from './CommunityUpgradeInProgressDto';
import type { ListOfCommunityUpgradeStateDto } from './ListOfCommunityUpgradeStateDto';

/**
 * Profile-level community upgrades state
 */
export interface CommunityUpgradesDto {
	currentlyUpgrading?: CommunityUpgradeInProgressDto | null;
	upgradeStates: ListOfCommunityUpgradeStateDto;
}
