/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface CommentResponse {
	id: number;
	sqid: string;
	/** @nullable */
	parentId?: number | null;
	content: string;
	/** @nullable */
	draftContent?: string | null;
	authorId: string;
	authorName: string;
	/** @nullable */
	authorAvatar?: string | null;
	createdAt: string;
	/** @nullable */
	editedAt?: string | null;
	score: number;
	/** @nullable */
	liftedElementId?: string | null;
	/** @nullable */
	userVote?: number | null;
	isPending: boolean;
	isDeleted: boolean;
	isEdited: boolean;
	isEditedByAdmin: boolean;
	hasPendingEdit: boolean;
}
