/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface ConfiguredProductFeaturesDto {
	/**
	 * Name of weight style to use.
	 * @nullable
	 */
	weightStyle?: number | null;
	/**
	 * Ability to override other's weight styles.
	 * @nullable
	 */
	weightStyleOverride?: boolean | null;
	/**
	 * Embed color for the bot.
	 * @maxLength 6
	 * @nullable
	 */
	embedColor?: string | null;
	/**
	 * Show "More Info" on weight command by default.
	 * @nullable
	 */
	moreInfoDefault?: boolean | null;
	/**
	 * If shop promotions should be hidden.
	 * @nullable
	 */
	hideShopPromotions?: boolean | null;
	/**
	 * Custom name emoji URL.
	 * @maxLength 256
	 * @nullable
	 */
	emojiUrl?: string | null;
}
