/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface ContestParticipationDto {
	crop: string;
	/** Timestamp of the contest in seconds since unix epoch. */
	timestamp: bigint;
	collected: number;
	position: number;
	participants: number;
	/** @nullable */
	medal?: string | null;
}
