/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuthorDto } from './AuthorDto';
import type { ContentReportStatus } from './ContentReportStatus';
import type { ContentReportTargetType } from './ContentReportTargetType';

export interface ContentReportDto {
	id: number;
	targetType: ContentReportTargetType;
	targetId: number;
	status: ContentReportStatus;
	reason: string;
	createdAt: string;
	/** @nullable */
	reviewedAt?: string | null;
	/** @nullable */
	resolutionNote?: string | null;
	reporter: AuthorDto;
	targetLabel: string;
	/** @nullable */
	targetUrl?: string | null;
}
