/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { CropSettingsOfString } from './CropSettingsOfString';

export interface ContestPingsFeatureDto {
	enabled: boolean;
	/** @nullable */
	guildId?: string | null;
	/** @nullable */
	channelId?: string | null;
	/** @nullable */
	alwaysPingRole?: string | null;
	cropPingRoles?: CropSettingsOfString | null;
	delaySeconds: number;
	/** @nullable */
	disabledReason?: string | null;
}
