/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { CreateEventDtoType } from './CreateEventDtoType';

export interface CreateEventDto {
	/**
	 * The name of the event
	 * @minLength 1
	 * @maxLength 64
	 */
	name: string;
	/**
	 * The type of the event
	 * @nullable
	 */
	type?: CreateEventDtoType;
	/**
	 * The Discord server id as a string for the event
	 * @minLength 1
	 */
	guildId: string;
	/**
	 * An optional description for the event
	 * @maxLength 1024
	 * @nullable
	 */
	description?: string | null;
	/**
	 * An optional set of rules for the event
	 * @maxLength 1024
	 * @nullable
	 */
	rules?: string | null;
	/**
	 * An optional description of prizes for the event
	 * @maxLength 1024
	 * @nullable
	 */
	prizeInfo?: string | null;
	/** Unix timestamp for the start time of the event in seconds */
	startTime: bigint;
	/** Unix timestamp for the end time of the event in seconds */
	endTime: bigint;
	/**
	 * Unix timestamp for the latest time a new member can join the event in seconds
	 * @nullable
	 */
	joinTime?: bigint | null;
	/**
	 * Currently unused
	 * @nullable
	 */
	dynamicStartTime?: boolean | null;
	/**
	 * A Discord role id that is required to participate in the event
	 * @maxLength 24
	 * @nullable
	 */
	requiredRole?: string | null;
	/**
	 * A Discord role id that is blocked from participating in the event
	 * @maxLength 24
	 * @nullable
	 */
	blockedRole?: string | null;
	/** Max amount of teams allowed in the event, 0 if solo event, -1 if unlimited */
	maxTeams: number;
	/** Max amount of members allowed in a team, 0 if solo event, -1 if unlimited */
	maxTeamMembers: number;
}
