/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfString } from './ListOfString';

export interface CreateEventTeamDto {
	name?: ListOfString | null;
	/**
	 * @maxLength 7
	 * @nullable
	 */
	color?: string | null;
}
