/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { WeightStyleData } from './WeightStyleData';

export interface CreateStyleRequest {
	/**
	 * @maxLength 64
	 * @nullable
	 */
	styleFormatter?: string | null;
	/**
	 * @minLength 0
	 * @maxLength 64
	 */
	name: string;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	collection?: string | null;
	/**
	 * @maxLength 1024
	 * @nullable
	 */
	description?: string | null;
	/**
	 * @minLength 1
	 */
	data: WeightStyleData;
}
