/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { CrimsonIsleStatsDtoKuudraCompletions } from './CrimsonIsleStatsDtoKuudraCompletions';
import type { CrimsonIsleStatsDtoKuudraHighestWaves } from './CrimsonIsleStatsDtoKuudraHighestWaves';
import type { CrimsonIsleStatsDtoDojoTests } from './CrimsonIsleStatsDtoDojoTests';

export interface CrimsonIsleStatsDto {
	/** @nullable */
	selectedFaction?: string | null;
	barbariansReputation: number;
	magesReputation: number;
	kuudraCompletions: CrimsonIsleStatsDtoKuudraCompletions;
	kuudraHighestWaves: CrimsonIsleStatsDtoKuudraHighestWaves;
	/** @nullable */
	highestKuudraTier?: string | null;
	totalKuudraRuns: number;
	dojoTests: CrimsonIsleStatsDtoDojoTests;
	dojoPointsTotal: number;
}
