/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface CropSettingsOfString {
	/** @nullable */
	cactus?: string | null;
	/** @nullable */
	carrot?: string | null;
	/** @nullable */
	potato?: string | null;
	/** @nullable */
	wheat?: string | null;
	/** @nullable */
	melon?: string | null;
	/** @nullable */
	pumpkin?: string | null;
	/** @nullable */
	mushroom?: string | null;
	/** @nullable */
	cocoaBeans?: string | null;
	/** @nullable */
	sugarCane?: string | null;
	/** @nullable */
	netherWart?: string | null;
}
