/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface CropSettingsOfInt32 {
	cactus: number;
	carrot: number;
	potato: number;
	wheat: number;
	melon: number;
	pumpkin: number;
	mushroom: number;
	cocoaBeans: number;
	sugarCane: number;
	netherWart: number;
}
