/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type Crop = (typeof Crop)[keyof typeof Crop];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Crop = {
	Cactus: 0,
	Carrot: 1,
	CocoaBeans: 2,
	Melon: 3,
	Mushroom: 4,
	NetherWart: 5,
	Potato: 6,
	Pumpkin: 7,
	SugarCane: 8,
	Wheat: 9,
	Seeds: 10,
} as const;
