/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfGuildJacobLeaderboardEntry } from './ListOfGuildJacobLeaderboardEntry';

export interface CropRecords {
	cactus: ListOfGuildJacobLeaderboardEntry;
	carrot: ListOfGuildJacobLeaderboardEntry;
	potato: ListOfGuildJacobLeaderboardEntry;
	wheat: ListOfGuildJacobLeaderboardEntry;
	melon: ListOfGuildJacobLeaderboardEntry;
	pumpkin: ListOfGuildJacobLeaderboardEntry;
	mushroom: ListOfGuildJacobLeaderboardEntry;
	cocoaBeans: ListOfGuildJacobLeaderboardEntry;
	sugarCane: ListOfGuildJacobLeaderboardEntry;
	netherWart: ListOfGuildJacobLeaderboardEntry;
	sunflower: ListOfGuildJacobLeaderboardEntry;
	moonflower: ListOfGuildJacobLeaderboardEntry;
	wildRose: ListOfGuildJacobLeaderboardEntry;
}
