/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndMemberFortuneSettingsDto } from './DictionaryOfStringAndMemberFortuneSettingsDto';

/**
 * Member fortune settings for each minecraft account, then each profile.
 */
export interface DictionaryOfStringAndDictionaryOfStringAndMemberFortuneSettingsDto {
	[key: string]: DictionaryOfStringAndMemberFortuneSettingsDto;
}
