/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { DragonFightDataMostDamage } from './DragonFightDataMostDamage';
import type { DragonFightDataFastestKill } from './DragonFightDataFastestKill';
import type { DragonFightDataAmountSummoned } from './DragonFightDataAmountSummoned';
import type { DragonFightDataHighestRank } from './DragonFightDataHighestRank';

export interface DragonFightData {
	enderCrystalsDestroyed: number;
	mostDamage: DragonFightDataMostDamage;
	fastestKill: DragonFightDataFastestKill;
	amountSummoned: DragonFightDataAmountSummoned;
	highestRank: DragonFightDataHighestRank;
}
