/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { DungeonsStatsDtoClassExperience } from './DungeonsStatsDtoClassExperience';
import type { DungeonsStatsDtoClassLevels } from './DungeonsStatsDtoClassLevels';
import type { DungeonsStatsDtoFloors } from './DungeonsStatsDtoFloors';
import type { DungeonsStatsDtoMasterFloors } from './DungeonsStatsDtoMasterFloors';
import type { DungeonsStatsDtoMostDamage } from './DungeonsStatsDtoMostDamage';
import type { DungeonsStatsDtoMostHealing } from './DungeonsStatsDtoMostHealing';

export interface DungeonsStatsDto {
	catacombsExperience: number;
	catacombsLevel: number;
	catacombsProgress: number;
	/** @nullable */
	selectedClass?: string | null;
	secretsFound: bigint;
	classExperience: DungeonsStatsDtoClassExperience;
	classLevels: DungeonsStatsDtoClassLevels;
	classAverage: number;
	/** Per-floor stats for normal Catacombs (keyed by floor number, e.g. "0" = Entrance, "1" = Floor 1, etc.) */
	floors: DungeonsStatsDtoFloors;
	/** Per-floor stats for Master Catacombs (keyed by floor number) */
	masterFloors: DungeonsStatsDtoMasterFloors;
	/**
	 * Most damage dealt by class (keyed by floor number)
	 * @nullable
	 */
	mostDamage?: DungeonsStatsDtoMostDamage;
	/**
	 * Most healing done (keyed by floor number)
	 * @nullable
	 */
	mostHealing?: DungeonsStatsDtoMostHealing;
}
