/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { DictionaryOfStringAndListOfDungeonBestRunResponse } from './DictionaryOfStringAndListOfDungeonBestRunResponse';

export interface DungeonData {
	experience: number;
	highest_tier_completed: number;
	tier_completions: DictionaryOfStringAndDouble;
	times_played: DictionaryOfStringAndDouble;
	best_score: DictionaryOfStringAndDouble;
	mobs_killed: DictionaryOfStringAndDouble;
	most_mobs_killed: DictionaryOfStringAndDouble;
	watcher_kills: DictionaryOfStringAndDouble;
	most_healing: DictionaryOfStringAndDouble;
	fastest_time: DictionaryOfStringAndDouble;
	fastest_time_s: DictionaryOfStringAndDouble;
	fastest_time_s_plus: DictionaryOfStringAndDouble;
	most_damage_tank: DictionaryOfStringAndDouble;
	most_damage_mage: DictionaryOfStringAndDouble;
	most_damage_healer: DictionaryOfStringAndDouble;
	most_damage_archer: DictionaryOfStringAndDouble;
	milestone_completions: DictionaryOfStringAndDouble;
	best_runs?: DictionaryOfStringAndListOfDungeonBestRunResponse | null;
}
