/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export interface DungeonBestRunResponse {
	timestamp: bigint;
	score_exploration: number;
	score_speed: number;
	score_skill: number;
	score_bonus: number;
	/** @nullable */
	dungeon_class?: string | null;
	elapsed_time: bigint;
	mobs_killed: number;
	secrets_found: number;
	damage_dealt: number;
	deaths: number;
	ally_healing: number;
	damage_mitigated: number;
	teammates: string[];
}
