/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { DungeonBestRun } from './DungeonBestRun';

export interface DungeonFloorStatsDto {
	completions: number;
	fastestTime: number;
	fastestTimeS: number;
	fastestTimeSPlus: number;
	bestScore: number;
	mobsKilled: number;
	/** @nullable */
	bestRuns?: DungeonBestRun[] | null;
}
