/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EditProductDtoFeatures } from './EditProductDtoFeatures';

export interface EditProductDto {
	/**
	 * Description of the product
	 * @maxLength 1024
	 * @nullable
	 */
	description?: string | null;
	/**
	 * If the product is available for purchase
	 * @nullable
	 */
	available?: boolean | null;
	/**
	 * Product price in USD cents
	 * @nullable
	 */
	price?: number | null;
	/**
	 * Features of the product
	 * @nullable
	 */
	features?: EditProductDtoFeatures;
	/**
	 * Unix seconds timestamp of release date
	 * @nullable
	 */
	releasedAt?: string | null;
}
