/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EditEventDtoWeightData } from './EditEventDtoWeightData';
import type { EditEventDtoMedalData } from './EditEventDtoMedalData';
import type { EditEventDtoPestData } from './EditEventDtoPestData';
import type { EditEventDtoCollectionData } from './EditEventDtoCollectionData';

export interface EditEventDto {
	/** @nullable */
	name?: string | null;
	/** @nullable */
	type?: string | null;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	rules?: string | null;
	/** @nullable */
	prizeInfo?: string | null;
	/** @nullable */
	startTime?: bigint | null;
	/** @nullable */
	joinTime?: bigint | null;
	/** @nullable */
	endTime?: bigint | null;
	/** @nullable */
	dynamicStartTime?: boolean | null;
	/** @nullable */
	active?: boolean | null;
	/** @nullable */
	requiredRole?: string | null;
	/** @nullable */
	blockedRole?: string | null;
	/** @nullable */
	guildId?: string | null;
	/** @nullable */
	weightData?: EditEventDtoWeightData;
	/** @nullable */
	medalData?: EditEventDtoMedalData;
	/** @nullable */
	pestData?: EditEventDtoPestData;
	/** @nullable */
	collectionData?: EditEventDtoCollectionData;
}
