/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EndedAuctionDtoSeller } from './EndedAuctionDtoSeller';
import type { EndedAuctionDtoBuyer } from './EndedAuctionDtoBuyer';
import type { EndedAuctionDtoItem } from './EndedAuctionDtoItem';

export interface EndedAuctionDto {
	auctionId: string;
	sellerUuid: string;
	sellerProfileUuid: string;
	/** @nullable */
	seller?: EndedAuctionDtoSeller;
	buyerUuid: string;
	buyerProfileUuid: string;
	/** @nullable */
	buyer?: EndedAuctionDtoBuyer;
	timestamp: bigint;
	price: bigint;
	count: number;
	bin: boolean;
	/** @nullable */
	skyblockId?: string | null;
	variantKey: string;
	/** @nullable */
	itemUuid?: string | null;
	/** @nullable */
	item?: EndedAuctionDtoItem;
}
