/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type EntitlementType = (typeof EntitlementType)[keyof typeof EntitlementType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntitlementType = {
	Purchase: 1,
	PremiumSubscription: 2,
	DeveloperGift: 3,
	TestModePurchase: 4,
	FreePurchase: 5,
	UserGift: 6,
	PremiumPurchase: 7,
	ApplicationSubscription: 8,
} as const;
