/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EntitlementType } from './EntitlementType';
import type { EntitlementTarget } from './EntitlementTarget';
import type { ProductDto } from './ProductDto';

export interface EntitlementDto {
	/** Entitlement ID */
	id: string;
	/** Type of entitlement */
	type: EntitlementType;
	/** Target of entitlement.
0 = None
1 = User
2 = Guild */
	target: EntitlementTarget;
	/** SKU ID of the product */
	productId: string;
	/** Product details */
	product: ProductDto;
	deleted: boolean;
	/**
	 * Consumed status of the entitlement if applicable
	 * @nullable
	 */
	consumed?: boolean | null;
	/**
	 * Start date of the entitlement
	 * @nullable
	 */
	startDate?: string | null;
	/**
	 * End date of the entitlement
	 * @nullable
	 */
	endDate?: string | null;
}
