/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EventType } from './EventType';
import type { ImageAttachmentDto } from './ImageAttachmentDto';

export interface EventDetailsDto {
	/** Event id as a string */
	id: string;
	/** Name of the event */
	name: string;
	type: EventType;
	/**
	 * Team mode of the event
	 * @nullable
	 */
	mode?: string | null;
	/**
	 * Event description
	 * @nullable
	 */
	description?: string | null;
	/**
	 * Event rules
	 * @nullable
	 */
	rules?: string | null;
	/**
	 * Event prize information
	 * @nullable
	 */
	prizeInfo?: string | null;
	banner?: ImageAttachmentDto | null;
	/**
	 * Start time of the event as a string in Unix seconds
	 * @nullable
	 */
	startTime?: string | null;
	/**
	 * Join time of the event as a string in Unix seconds
	 * @nullable
	 */
	joinUntilTime?: string | null;
	/**
	 * End time of the event as a string in Unix seconds
	 * @nullable
	 */
	endTime?: string | null;
	/** Currently unused */
	dynamicStartTime: boolean;
	/** Event status */
	active: boolean;
	/** Event approval status */
	approved: boolean;
	/** Max amount of teams allowed in the event, 0 if solo event, -1 if unlimited */
	maxTeams: number;
	/** Max amount of members allowed in a team, 0 if solo event, -1 if unlimited */
	maxTeamMembers: number;
	/**
	 * Discord role id required to participate in the event
	 * @nullable
	 */
	requiredRole?: string | null;
	/**
	 * Discord role id blocked from participating in the event
	 * @nullable
	 */
	blockedRole?: string | null;
	/**
	 * Discord server id as a string
	 * @nullable
	 */
	guildId?: string | null;
	/** Data specific to the event */
	data?: unknown;
}
