/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EventMemberDto } from './EventMemberDto';

export interface EventTeamWithMembersDto {
	id: number;
	/** @nullable */
	eventId?: string | null;
	/** @nullable */
	name?: string | null;
	/** @nullable */
	color?: string | null;
	/** @nullable */
	score?: string | null;
	/** @nullable */
	ownerId?: string | null;
	/** @nullable */
	ownerUuid?: string | null;
	members: EventMemberDto[];
	/**
	 * Join code for the team, only populated if authenticated user is the owner
	 * @nullable
	 */
	joinCode?: string | null;
}
