/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type EventMemberStatus = (typeof EventMemberStatus)[keyof typeof EventMemberStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventMemberStatus = {
	Inactive: 0,
	Active: 1,
	Left: 2,
	Disqualified: 3,
} as const;
