/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { DictionaryOfStringAndInt32 } from './DictionaryOfStringAndInt32';
import type { DictionaryOfStringAndInt64 } from './DictionaryOfStringAndInt64';
import type { PestsDto } from './PestsDto';

export interface FarmingWeightDto {
	totalWeight: number;
	crops?: DictionaryOfStringAndInt64 | null;
	cropWeight: DictionaryOfStringAndDouble;
	bonusWeight: DictionaryOfStringAndDouble;
	uncountedCrops: DictionaryOfStringAndInt32;
	pests: PestsDto;
	lastUpdated: bigint;
}
