/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { FarmingWeightWithProfileDtoCrops } from './FarmingWeightWithProfileDtoCrops';
import type { FarmingWeightWithProfileDtoCropWeight } from './FarmingWeightWithProfileDtoCropWeight';
import type { FarmingWeightWithProfileDtoBonusWeight } from './FarmingWeightWithProfileDtoBonusWeight';
import type { FarmingWeightWithProfileDtoUncountedCrops } from './FarmingWeightWithProfileDtoUncountedCrops';
import type { PestsDto } from './PestsDto';

export interface FarmingWeightWithProfileDto {
	profileId: string;
	profileName: string;
	totalWeight: number;
	/** @nullable */
	crops?: FarmingWeightWithProfileDtoCrops;
	cropWeight: FarmingWeightWithProfileDtoCropWeight;
	bonusWeight: FarmingWeightWithProfileDtoBonusWeight;
	uncountedCrops: FarmingWeightWithProfileDtoUncountedCrops;
	pests: PestsDto;
	lastUpdated: bigint;
}
