/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuthorDto } from './AuthorDto';
import type { FeedbackPostStatus } from './FeedbackPostStatus';

export interface FeedbackUpdateDto {
	id: number;
	author: AuthorDto;
	content: string;
	previousStatus?: FeedbackPostStatus | null;
	newStatus?: FeedbackPostStatus | null;
	createdAt: string;
}
