/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ForagingStatsDtoNodes } from './ForagingStatsDtoNodes';
import type { ForagingStatsDtoNodeToggles } from './ForagingStatsDtoNodeToggles';
import type { ForagingStatsDtoTreeGifts } from './ForagingStatsDtoTreeGifts';
import type { ForagingStatsDtoPersonalBests } from './ForagingStatsDtoPersonalBests';

export interface ForagingStatsDto {
	hotfExperience: number;
	hotfLevel: number;
	hotfProgress: number;
	centerOfTheForestLevel: number;
	/** @nullable */
	selectedAxeAbility?: string | null;
	hotfTokensSpent: number;
	forestsWhispers: number;
	forestsWhispersSpent: number;
	nodes: ForagingStatsDtoNodes;
	nodeToggles: ForagingStatsDtoNodeToggles;
	fishFamilyCollected: number;
	hinaChapterTier: number;
	treeGifts: ForagingStatsDtoTreeGifts;
	personalBests: ForagingStatsDtoPersonalBests;
}
