/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndBoolean } from './DictionaryOfStringAndBoolean';
import type { DictionaryOfStringAndInt32 } from './DictionaryOfStringAndInt32';
import type { DictionaryOfStringAndTreeGiftData } from './DictionaryOfStringAndTreeGiftData';

export interface ForagingStatsDto {
	hotfExperience: number;
	hotfLevel: number;
	hotfProgress: number;
	centerOfTheForestLevel: number;
	/** @nullable */
	selectedAxeAbility?: string | null;
	hotfTokensSpent: number;
	forestsWhispers: number;
	forestsWhispersSpent: number;
	nodes: DictionaryOfStringAndInt32;
	nodeToggles: DictionaryOfStringAndBoolean;
	fishFamilyCollected: number;
	hinaChapterTier: number;
	treeGifts: DictionaryOfStringAndTreeGiftData;
	personalBests: DictionaryOfStringAndInt32;
}
