/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { FrameStyleDataLeaderboard } from './FrameStyleDataLeaderboard';
import type { FrameStyleDataNameCard } from './FrameStyleDataNameCard';

export interface FrameStyleData {
	/** @nullable */
	leaderboard?: FrameStyleDataLeaderboard;
	/** @nullable */
	nameCard?: FrameStyleDataNameCard;
}
