/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { FrameStyleDataDtoLeaderboard } from './FrameStyleDataDtoLeaderboard';
import type { FrameStyleDataDtoNameCard } from './FrameStyleDataDtoNameCard';

export interface FrameStyleDataDto {
	/** @nullable */
	leaderboard?: FrameStyleDataDtoLeaderboard;
	/** @nullable */
	nameCard?: FrameStyleDataDtoNameCard;
}
