/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { CropSettingsOfString } from './CropSettingsOfString';
import type { CropSettingsOfInt32 } from './CropSettingsOfInt32';
import type { ComposterDto } from './ComposterDto';
import type { GardenDtoVisitors } from './GardenDtoVisitors';

export interface GardenDto {
	/** Profile ID */
	profileId: string;
	/** Garden experience */
	experience: number;
	/** Total completed visitors */
	completedVisitors: number;
	/** Unique visitors unlocked */
	uniqueVisitors: number;
	/** Crops counted towards milestones */
	crops: CropSettingsOfString;
	/** Crop upgrades */
	cropUpgrades: CropSettingsOfInt32;
	/** List of unlocked plots */
	plots: string[];
	/** Composter data */
	composter: ComposterDto;
	/** Visitor data */
	visitors: GardenDtoVisitors;
	/** Last save time in unix seconds */
	lastSave: string;
}
