/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ComposterDto } from './ComposterDto';
import type { CropSettingsOfInt32 } from './CropSettingsOfInt32';
import type { CropSettingsOfString } from './CropSettingsOfString';
import type { DictionaryOfStringAndGreenhouseUpgradeCatalogDto } from './DictionaryOfStringAndGreenhouseUpgradeCatalogDto';
import type { DictionaryOfStringAndVisitorDto } from './DictionaryOfStringAndVisitorDto';
import type { GardenUpgradesDto } from './GardenUpgradesDto';
import type { ListOfGreenhouseSlotUnlock } from './ListOfGreenhouseSlotUnlock';
import type { ListOfString } from './ListOfString';

export interface GardenDto {
	/** Profile ID */
	profileId: string;
	/** Garden experience */
	experience: bigint;
	/** Garden level (computed from XP) */
	gardenLevel: number;
	/** Progress towards the next garden level (0-1) */
	gardenProgress: number;
	/** Total completed visitors */
	completedVisitors: number;
	/** Unique visitors unlocked */
	uniqueVisitors: number;
	crops: CropSettingsOfString;
	cropMilestoneLevels: CropSettingsOfInt32;
	cropUpgrades: CropSettingsOfInt32;
	plots: ListOfString;
	composter: ComposterDto;
	visitors: DictionaryOfStringAndVisitorDto;
	/** Unix timestamp of the last greenhouse growth stage in milliseconds */
	lastGrowthStageTime: bigint;
	greenhouseSlots: ListOfGreenhouseSlotUnlock;
	gardenUpgrades: GardenUpgradesDto;
	greenhouseUpgradeCatalog: DictionaryOfStringAndGreenhouseUpgradeCatalogDto;
	gardenToolIds: ListOfString;
	/** Last save time in unix seconds */
	lastSave: string;
}
