/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { GreenhouseUpgradeCatalogDto } from './GreenhouseUpgradeCatalogDto';

/**
 * Catalog of greenhouse upgrade definitions sourced from staged Skyblock stats metadata.
Includes per-level costs, max level, and presentation details.
 */
export type GardenDtoGreenhouseUpgradeCatalog = { [key: string]: GreenhouseUpgradeCatalogDto };
