/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface GetGuideResponse {
	id: number;
	slug: string;
	title: string;
	description: string;
	content: string;
	authorName: string;
	authorId: bigint;
	/** @nullable */
	authorUuid?: string | null;
	createdAt: string;
	score: number;
	viewCount: number;
	tags: string[];
	isDraft: boolean;
	/**
	 * Current user's vote on this guide (+1, -1, or null if not voted).
	 * @nullable
	 */
	userVote?: number | null;
	/**
	 * Whether the current user has bookmarked this guide.
	 * @nullable
	 */
	isBookmarked?: boolean | null;
	/**
	 * Reason for rejection (only present for rejected guides visible to author).
	 * @nullable
	 */
	rejectionReason?: string | null;
}
