/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GlobalProgressInterval } from './GlobalProgressInterval';

export type GetGlobalProgressParams = {
	/**
	 * Inclusive lower UTC bucket, expressed as a Unix timestamp in seconds.
	 * @nullable
	 */
	from?: bigint | null;
	/**
	 * Inclusive upper UTC bucket, expressed as a Unix timestamp in seconds.
	 * @nullable
	 */
	to?: bigint | null;
	interval: GlobalProgressInterval;
};
