/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { RemovedFilter } from './RemovedFilter';

export type GetMultiplePlayerRanksParams = {
	/**
	 * Ids of leaderboards (comma-separated)
	 */
	leaderboards: string;
	/**
	 * Include upcoming players
	 * @nullable
	 */
	includeUpcoming?: boolean | null;
	/**
	 * Amount of upcoming players to include (max 10).
	 * @nullable
	 */
	upcoming?: number | null;
	/**
	 * Amount of passed players to include (max 3).
	 * @nullable
	 */
	previous?: number | null;
	/**
	 * Start at a specified rank for upcoming players
	 * @nullable
	 */
	atRank?: number | null;
	/**
	 * Time interval key of a monthly leaderboard. Format: yyyy-MM
	 * @nullable
	 */
	interval?: string | null;
	/**
 * Game mode to filter leaderboard by. Leave empty to get all modes.
Options: "ironman", "island", "classic"
 * @nullable
 */
	mode?: string | null;
	/**
 * Removed filter to get leaderboard entries that have been removed from the leaderboard.
Default is profiles that have not been removed/wiped.
0 = Not Removed
1 = Removed
2 = All
 * @nullable
 */
	removed?: RemovedFilter | null;
};
