/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { RemovedFilter } from './RemovedFilter';

export type GetProfileRank2Params = {
	/**
	 * @nullable
	 */
	includeUpcoming?: boolean | null;
	/**
	 * @nullable
	 */
	upcoming?: number | null;
	/**
	 * @nullable
	 */
	atRank?: number | null;
	/**
	 * @nullable
	 */
	new?: boolean | null;
	/**
	 * @nullable
	 */
	interval?: string | null;
	/**
	 * @nullable
	 */
	mode?: string | null;
	/**
	 * @nullable
	 */
	removed?: RemovedFilter | null;
};
