/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { TebexRecipientSnapshot } from './TebexRecipientSnapshot';

export interface GiftItemStateDto {
	/** @nullable */
	recipientId?: string | null;
	/** @nullable */
	recipientGuildId?: string | null;
	/** @nullable */
	recipientType?: string | null;
	/** @nullable */
	recipientResolutionStatus?: string | null;
	/** @nullable */
	claimExpiresAt?: string | null;
	recipientSnapshot?: TebexRecipientSnapshot | null;
	isReassignable: boolean;
	/** @nullable */
	canAdminResolveRecipient?: boolean | null;
}
