/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { DictionaryOfStringAndInt64 } from './DictionaryOfStringAndInt64';
import type { GlobalProgressCoverage } from './GlobalProgressCoverage';

export interface GlobalCropProgressPoint {
	timestamp: bigint;
	updatedAt: bigint;
	isPartial: boolean;
	crops: DictionaryOfStringAndInt64;
	npcPrices: DictionaryOfStringAndDouble;
	npcValues: DictionaryOfStringAndDouble;
	totalCropNpcValue: number;
	npcPricesComplete: boolean;
	coverage: GlobalProgressCoverage;
}
