/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GreenhouseActionInput } from './GreenhouseActionInput';
import type { GreenhouseScheduledActionGuard } from './GreenhouseScheduledActionGuard';
import type { GreenhouseScheduledActionKind } from './GreenhouseScheduledActionKind';
import type { ListOfString } from './ListOfString';

export interface GreenhouseScheduledActionInput {
	kind: GreenhouseScheduledActionKind;
	guard: GreenhouseScheduledActionGuard;
	action?: GreenhouseActionInput | null;
	waterThreshold: number;
	plantIds: ListOfString;
	/** @nullable */
	minimumPlantStage?: number | null;
}
