/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface GreenhouseChorusTargetCountFrontierDto {
	targetCount: number;
	movementCells: number;
	initialMutationFreeDestinationCells: number;
	expectedPeakPopulation: number;
	expectedMinimumMutationFreeDestinationCells: number;
	expectedHarvestedCount: number;
	expectedHarvestedPerDay: number;
	expectedEffectiveHarvestedCount: number;
	expectedEffectiveHarvestedPerDay: number;
	destructiveReplacementProbability: number;
	saturationProbability: number;
	immuneHarvestPercentage: number;
	selected: boolean;
	lifecycleMode: string;
	netProfitPerDay: number;
	/** @nullable */
	netProfitPerSetup: number | null;
	economicSetupCost: number;
}
