/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { DictionaryOfStringAndGreenhouseGardenChipInput } from './DictionaryOfStringAndGreenhouseGardenChipInput';
import type { DictionaryOfStringAndInt32 } from './DictionaryOfStringAndInt32';
import type { GreenhouseHarvestSetupInput } from './GreenhouseHarvestSetupInput';

export interface GreenhouseAccountInput {
	growthSpeedUpgradeLevel: number;
	plantYieldUpgradeLevel: number;
	plotLimitUpgradeLevel: number;
	cropGrowth: number;
	miningFortune: number;
	mutationChanceMultiplier: number;
	farmingWisdom: number;
	harvestSetup: GreenhouseHarvestSetupInput;
	gardenChips: DictionaryOfStringAndGreenhouseGardenChipInput;
	attributes: DictionaryOfStringAndInt32;
	customModifiers: DictionaryOfStringAndDouble;
}
