/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { GreenhouseAccountInput } from './GreenhouseAccountInput';
import type { GreenhouseMarketInput } from './GreenhouseMarketInput';
import type { ListOfGreenhousePlotInput } from './ListOfGreenhousePlotInput';

export interface GreenhouseStateInput {
	catalogVersion: string;
	plots: ListOfGreenhousePlotInput;
	account: GreenhouseAccountInput;
	inventory: DictionaryOfStringAndDouble;
	coins: number;
	market: GreenhouseMarketInput;
}
