/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfGreenhouseMovingSupportSetupPhaseDto } from './ListOfGreenhouseMovingSupportSetupPhaseDto';
import type { ListOfString } from './ListOfString';

export interface GreenhouseMovingSupportSetupDto {
	movingSupportPlantIds: ListOfString;
	solverPasses: number;
	elapsedMilliseconds: number;
	fixedAssignmentValidationMilliseconds: number;
	totalSimulatedWaitHours: number;
	/** @nullable */
	setupVisitIntervalGrowthStages?: number | null;
	setupWaitIncludedInEconomics: boolean;
	setupOnlyCashCost: number;
	setupOnlyEconomicCost: number;
	setupOnlyRemovalOpportunityCost: number;
	setupOnlyRequiredCapital: number;
	setupOnlyPlacementActionCount: number;
	setupOnlyCleanupActionCount: number;
	playerActionDurationModeled: boolean;
	phases: ListOfGreenhouseMovingSupportSetupPhaseDto;
}
