/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfGreenhouseConflictDto } from './ListOfGreenhouseConflictDto';
import type { ListOfGreenhousePlantInspectionDto } from './ListOfGreenhousePlantInspectionDto';
import type { ListOfGreenhouseSpawnCandidateDto } from './ListOfGreenhouseSpawnCandidateDto';
import type { ListOfGreenhouseWarningDto } from './ListOfGreenhouseWarningDto';

export interface GreenhouseAnalysisResponse {
	catalogVersion: string;
	spawnCandidates: ListOfGreenhouseSpawnCandidateDto;
	conflicts: ListOfGreenhouseConflictDto;
	plantInspections: ListOfGreenhousePlantInspectionDto;
	warnings: ListOfGreenhouseWarningDto;
}
