/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GreenhouseProfitSnapshotStatus } from './GreenhouseProfitSnapshotStatus';
import type { ListOfGreenhouseProfitSummaryDto } from './ListOfGreenhouseProfitSummaryDto';

export interface GreenhouseProfitRankingResponse {
	catalogVersion: string;
	calculatedAt: string;
	priceCapturedAt: string;
	priceSnapshotHash: string;
	inputHash: string;
	resultCacheHit: boolean;
	spatialSnapshotVersion: string;
	snapshotStatus: GreenhouseProfitSnapshotStatus;
	entries: ListOfGreenhouseProfitSummaryDto;
}
