/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfDictionaryOfStringAndInt32 } from './ListOfDictionaryOfStringAndInt32';

export interface GreenhouseUpgradeCatalogDto {
	name: string;
	rewardFormula: string;
	format: string;
	tooltip: string;
	maxLevel: number;
	upgrades: ListOfDictionaryOfStringAndInt32;
}
