/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { IReadOnlyListOfGreenhouseSupportingPlantDto } from './IReadOnlyListOfGreenhouseSupportingPlantDto';

export interface GreenhouseSpawnCandidateDto {
	mutationId: string;
	plot: number;
	x: number;
	z: number;
	width: number;
	height: number;
	spawnWeight: number;
	effectiveSpawnWeight: number;
	competingMutationWeight: number;
	blankWeight: number;
	selectionProbability: number;
	canFitFootprint: boolean;
	supportingPlants: IReadOnlyListOfGreenhouseSupportingPlantDto;
}
