/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfGreenhouseDropDto } from './ListOfGreenhouseDropDto';
import type { ListOfGreenhouseEffectDto } from './ListOfGreenhouseEffectDto';

export interface GreenhouseBaseCropDto {
	id: string;
	name: string;
	uniqueGroup: string;
	surface: string;
	stages: number;
	/** @nullable */
	decayHours?: number | null;
	drops: ListOfGreenhouseDropDto;
	effects: ListOfGreenhouseEffectDto;
	sowdust: number;
	farmingExperience: number;
}
