/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { GreenhouseSetupLifecycleDto } from './GreenhouseSetupLifecycleDto';
import type { ListOfGreenhouseSetupIngredientDto } from './ListOfGreenhouseSetupIngredientDto';

export interface GreenhouseEconomicsDto {
	objective: string;
	expectedScore: number;
	mode: string;
	/**
	 * Zero-revenue time spent establishing the published settled-state layout
	 *             before its productive lifecycle begins.
	 */
	setupDurationHours: number;
	/**
	 * For finite setups with an explicitly modeled pre-lifecycle phase,
	 *             productive useful lifetime plus setup duration. Null when no such phase is
	 *             modeled and for indefinitely self-sustaining layouts.
	 * @nullable
	 */
	economicCycleHours?: number | null;
	/** @nullable */
	netProfitPerSetup?: number | null;
	netProfitPerDay: number;
	cashSetupCost: number;
	economicSetupCost: number;
	requiredCapital: number;
	replacementCost: number;
	residualSupportValue: number;
	setupCostPerExpectedTarget: number;
	breakEvenTargetCount: number;
	/** @nullable */
	paybackHours?: number | null;
	newlyPlacedIngredientCount: number;
	retainedIngredientCount: number;
	setupCostsByIngredient: ListOfGreenhouseSetupIngredientDto;
	expectedHarvestRevenue: number;
	expectedRecurringCosts: number;
	expectedTargetRevenue: number;
	expectedSupportRevenue: number;
	expectedTargetCosts: number;
	expectedSupportAndMaintenanceCosts: number;
	expectedBaseCropRevenue: number;
	expectedRareDropRevenue: number;
	expectedBonusDropRevenue: number;
	expectedMobRewardRevenue: number;
	expectedMobGuaranteedDropRevenue: number;
	expectedMobShardRevenue: number;
	expectedItems: DictionaryOfStringAndDouble;
	expectedBonusDropItems: DictionaryOfStringAndDouble;
	expectedMobGuaranteedDropItems: DictionaryOfStringAndDouble;
	expectedMobShardItems: DictionaryOfStringAndDouble;
	lifecycle: GreenhouseSetupLifecycleDto;
}
