/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfGreenhouseDropDto } from './ListOfGreenhouseDropDto';
import type { ListOfGreenhouseEffectDto } from './ListOfGreenhouseEffectDto';
import type { ListOfGreenhouseSpawnConditionDto } from './ListOfGreenhouseSpawnConditionDto';

export interface GreenhouseMutationDto {
	id: string;
	name: string;
	rarity: string;
	surface: string;
	width: number;
	height: number;
	stages: number;
	requiresWater: boolean;
	spawnWeight: number;
	spawnSupportFactor: number;
	/** @nullable */
	decayHours?: number | null;
	harvestableFromStage: number;
	spawnConditions: ListOfGreenhouseSpawnConditionDto;
	drops: ListOfGreenhouseDropDto;
	effects: ListOfGreenhouseEffectDto;
	sowdust: number;
	farmingExperience: number;
	planningCapability: string;
	/** @nullable */
	unsupportedReason?: string | null;
}
