/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GreenhouseChorusLifecycleDto } from './GreenhouseChorusLifecycleDto';
import type { GreenhouseConfidenceDto } from './GreenhouseConfidenceDto';
import type { GreenhouseEconomicsDto } from './GreenhouseEconomicsDto';
import type { GreenhouseHarvestSetupDto } from './GreenhouseHarvestSetupDto';
import type { GreenhousePhaseTimingsDto } from './GreenhousePhaseTimingsDto';
import type { GreenhouseSolverStrategy } from './GreenhouseSolverStrategy';
import type { ListOfGreenhouseAssumptionDto } from './ListOfGreenhouseAssumptionDto';
import type { ListOfGreenhouseEconomicInputDto } from './ListOfGreenhouseEconomicInputDto';
import type { ListOfGreenhouseEffectPathDto } from './ListOfGreenhouseEffectPathDto';
import type { ListOfGreenhouseLayoutEditDto } from './ListOfGreenhouseLayoutEditDto';
import type { ListOfGreenhousePlannedPlantDto } from './ListOfGreenhousePlannedPlantDto';
import type { ListOfGreenhousePlannedTargetDto } from './ListOfGreenhousePlannedTargetDto';
import type { ListOfGreenhousePlantInspectionDto } from './ListOfGreenhousePlantInspectionDto';
import type { ListOfGreenhouseScheduleStepDto } from './ListOfGreenhouseScheduleStepDto';
import type { ListOfGreenhouseSupportStrategyInstructionDto } from './ListOfGreenhouseSupportStrategyInstructionDto';
import type { ListOfString } from './ListOfString';

export interface GreenhousePlanResultDto {
	strategy: GreenhouseSolverStrategy;
	targetMutationId: string;
	proofStatus: string;
	solverStrategy: string;
	isOptimal: boolean;
	targetCount: number;
	supportSlots: number;
	placements: ListOfGreenhousePlannedPlantDto;
	targets: ListOfGreenhousePlannedTargetDto;
	edits: ListOfGreenhouseLayoutEditDto;
	schedule: ListOfGreenhouseScheduleStepDto;
	supportInstructions: ListOfGreenhouseSupportStrategyInstructionDto;
	economics: GreenhouseEconomicsDto;
	harvestSetup: GreenhouseHarvestSetupDto;
	economicInputs: ListOfGreenhouseEconomicInputDto;
	confidence: GreenhouseConfidenceDto;
	effectPaths: ListOfGreenhouseEffectPathDto;
	plantInspections: ListOfGreenhousePlantInspectionDto;
	assumptions: ListOfGreenhouseAssumptionDto;
	warnings: ListOfString;
	timings: GreenhousePhaseTimingsDto;
	priceCapturedAt: string;
	priceSnapshotHash: string;
	chorusLifecycle?: GreenhouseChorusLifecycleDto | null;
}
