/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface GreenhouseEventDto {
	type: string;
	atHour: number;
	/** @nullable */
	plot: number | null;
	/** @nullable */
	x: number | null;
	/** @nullable */
	z: number | null;
	/** @nullable */
	itemId: string | null;
	amount: number;
	/** @nullable */
	message: string | null;
}
