/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface GreenhouseShellfruitTimingDto {
	growthCycleHours: number;
	expectedTotalHours: number;
	placedBlastberryArmCycles: number;
	/** @nullable */
	spawnProbabilityPerDraw?: number | null;
	/** @nullable */
	expectedSpawnDraws?: number | null;
	/** @nullable */
	ingredientBatchDrawCapacity?: number | null;
	/** @nullable */
	spawnSuccessProbabilityPerIngredientBatch?: number | null;
	/** @nullable */
	expectedIngredientBatches?: number | null;
	/** @nullable */
	naturalBlastberryGrowthCycles?: number | null;
	/** @nullable */
	expectedTotalGrowthCycles?: number | null;
}
