/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GreenhouseJobErrorDto } from './GreenhouseJobErrorDto';
import type { GreenhouseJobKind } from './GreenhouseJobKind';
import type { GreenhouseJobStatus } from './GreenhouseJobStatus';
import type { GreenhouseSimulationResultDto } from './GreenhouseSimulationResultDto';

export interface GreenhouseJobResponseOfGreenhouseSimulationResultDto {
	jobId: string;
	kind: GreenhouseJobKind;
	status: GreenhouseJobStatus;
	requestedAt: string;
	/** @nullable */
	startedAt?: string | null;
	/** @nullable */
	completedAt?: string | null;
	expiresAt: string;
	priceCapturedAt: string;
	priceSnapshotHash: string;
	/** @nullable */
	queuePosition?: number | null;
	result?: GreenhouseSimulationResultDto | null;
	error?: GreenhouseJobErrorDto | null;
}
