/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfGreenhouseCellPositionDto } from './ListOfGreenhouseCellPositionDto';
import type { ListOfGreenhouseShellfruitActionDto } from './ListOfGreenhouseShellfruitActionDto';
import type { ListOfGreenhouseShellfruitPlacementDto } from './ListOfGreenhouseShellfruitPlacementDto';
import type { ListOfGreenhouseShellfruitRemovalDto } from './ListOfGreenhouseShellfruitRemovalDto';
import type { ListOfGreenhouseShellfruitSurfaceChangeDto } from './ListOfGreenhouseShellfruitSurfaceChangeDto';

export interface GreenhouseShellfruitPhaseDto {
	order: number;
	kind: string;
	startTrigger: string;
	completionGuard: string;
	conditional: boolean;
	/** @nullable */
	repeatFromPhaseOrder?: number | null;
	resetsNaturalBlastberryCenters: boolean;
	automaticallyExecutable: boolean;
	expectedMutationDraws: number;
	growthCycles: number;
	simultaneous: boolean;
	placements: ListOfGreenhouseShellfruitPlacementDto;
	removals: ListOfGreenhouseShellfruitRemovalDto;
	surfaceChanges: ListOfGreenhouseShellfruitSurfaceChangeDto;
	affectedCells: ListOfGreenhouseCellPositionDto;
	actions: ListOfGreenhouseShellfruitActionDto;
}
