/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GuideAssetType } from './GuideAssetType';
import type { GuideLitematicDto } from './GuideLitematicDto';
import type { ImageAttachmentDto } from './ImageAttachmentDto';

export interface GuideAssetDto {
	id: string;
	type: GuideAssetType;
	fileName: string;
	contentType: string;
	sizeBytes: bigint;
	createdAt: string;
	image?: ImageAttachmentDto | null;
	litematic?: GuideLitematicDto | null;
}
