/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GuildFeaturesJacobLeaderboard } from './GuildFeaturesJacobLeaderboard';
import type { GuildFeaturesVerifiedRole } from './GuildFeaturesVerifiedRole';
import type { GuildFeaturesEventSettings } from './GuildFeaturesEventSettings';
import type { GuildFeaturesContestPings } from './GuildFeaturesContestPings';

export interface GuildFeatures {
	locked: boolean;
	jacobLeaderboardEnabled: boolean;
	/** @nullable */
	jacobLeaderboard?: GuildFeaturesJacobLeaderboard;
	verifiedRoleEnabled: boolean;
	/** @nullable */
	verifiedRole?: GuildFeaturesVerifiedRole;
	eventsEnabled: boolean;
	/** @nullable */
	eventSettings?: GuildFeaturesEventSettings;
	contestPingsEnabled: boolean;
	/** @nullable */
	contestPings?: GuildFeaturesContestPings;
}
