/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { CropRecords } from './CropRecords';

export interface GuildJacobLeaderboard {
	id: string;
	/** @nullable */
	channelId?: string | null;
	startCutoff: bigint;
	endCutoff: bigint;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	title?: string | null;
	active: boolean;
	/** @nullable */
	requiredRole?: string | null;
	/** @nullable */
	blockedRole?: string | null;
	/** @nullable */
	updateChannelId?: string | null;
	/** @nullable */
	updateRoleId?: string | null;
	pingForSmallImprovements: boolean;
	crops: CropRecords;
}
