/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { HypixelGuildMemberDetailsDtoGuild } from './HypixelGuildMemberDetailsDtoGuild';
import type { HypixelGuildMemberDetailsDtoExpHistory } from './HypixelGuildMemberDetailsDtoExpHistory';

export interface HypixelGuildMemberDetailsDto {
	/** @nullable */
	guild?: HypixelGuildMemberDetailsDtoGuild;
	/** @nullable */
	rank?: string | null;
	joinedAt: bigint;
	questParticipation: number;
	active: boolean;
	expHistory: HypixelGuildMemberDetailsDtoExpHistory;
}
