/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { HypixelInventoryDtoItems } from './HypixelInventoryDtoItems';
import type { HypixelInventoryDtoMetadata } from './HypixelInventoryDtoMetadata';

export interface HypixelInventoryDto {
	id: string;
	/** @maxLength 64 */
	name: string;
	/** Dictionary of slot to item mapping, null if the slot is empty */
	items: HypixelInventoryDtoItems;
	/** @nullable */
	metadata?: HypixelInventoryDtoMetadata;
}
