/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndInt64 } from './DictionaryOfStringAndInt64';
import type { HypixelGuildStat } from './HypixelGuildStat';

export interface HypixelGuildStatsFullDto {
	collections: DictionaryOfStringAndInt64;
	skills: DictionaryOfStringAndInt64;
	recordedAt: string;
	memberCount: number;
	hypixelLevel: HypixelGuildStat;
	skyblockExperience: HypixelGuildStat;
	skillLevel: HypixelGuildStat;
	slayerExperience: HypixelGuildStat;
	catacombsExperience: HypixelGuildStat;
	farmingWeight: HypixelGuildStat;
	networth: HypixelGuildStat;
}
