/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { HypixelGuildDetailsDtoStats } from './HypixelGuildDetailsDtoStats';

export interface HypixelGuildDetailsDto {
	id: string;
	name: string;
	createdAt: bigint;
	/** @nullable */
	tag?: string | null;
	/** @nullable */
	tagColor?: string | null;
	memberCount: number;
	lastUpdated: bigint;
	/** @nullable */
	stats?: HypixelGuildDetailsDtoStats;
	/** Populated when sorting guilds by a specific collection or skill */
	amount: number;
}
