/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ItemDto } from './ItemDto';
import type { HypixelInventoryDtoMetadata } from './HypixelInventoryDtoMetadata';

export interface HypixelInventoryDto {
	id: string;
	/** @maxLength 64 */
	name: string;
	items: ItemDto[];
	/** @nullable */
	metadata?: HypixelInventoryDtoMetadata;
}
