/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { HypixelGuildStat } from './HypixelGuildStat';
import type { HypixelGuildStatsFullDtoCollections } from './HypixelGuildStatsFullDtoCollections';
import type { HypixelGuildStatsFullDtoSkills } from './HypixelGuildStatsFullDtoSkills';

export interface HypixelGuildStatsFullDto {
	recordedAt: string;
	memberCount: number;
	hypixelLevel: HypixelGuildStat;
	skyblockExperience: HypixelGuildStat;
	skillLevel: HypixelGuildStat;
	slayerExperience: HypixelGuildStat;
	catacombsExperience: HypixelGuildStat;
	farmingWeight: HypixelGuildStat;
	networth: HypixelGuildStat;
	collections: HypixelGuildStatsFullDtoCollections;
	skills: HypixelGuildStatsFullDtoSkills;
}
