/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ImageSourceDto } from './ImageSourceDto';

/**
 * A dictionary of available image sources, keyed by a logical name (e.g., "small", "medium").
 */
export type ImageAttachmentDtoSources = { [key: string]: ImageSourceDto };
