/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { IncomingGuildChannelDto } from './IncomingGuildChannelDto';
import type { IncomingGuildRoleDto } from './IncomingGuildRoleDto';

export interface IncomingGuildDto {
	/** @nullable */
	id?: string | null;
	name: string;
	/** @nullable */
	icon?: string | null;
	/** @nullable */
	banner?: string | null;
	/** @nullable */
	permissions?: string | null;
	/** @nullable */
	botPermissions?: string | null;
	/** @nullable */
	features?: string[] | null;
	/** @nullable */
	channels?: IncomingGuildChannelDto[] | null;
	/** @nullable */
	roles?: IncomingGuildRoleDto[] | null;
}
