/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { InventoryItemMetaResponseNetworth } from './InventoryItemMetaResponseNetworth';

export interface InventoryItemMetaResponse {
	/**
	 * Texture Pack ID where the item texture is located
	 * @nullable
	 */
	packId?: string | null;
	/**
	 * Variant key for price lookups
	 * @nullable
	 */
	variantKey?: string | null;
	/**
	 * Networth calculation result for this item
	 * @nullable
	 */
	networth?: InventoryItemMetaResponseNetworth;
}
