/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

/**
 * Pet info if item is a pet
 */
export interface ItemPetInfoDto {
	type: string;
	active: boolean;
	exp: number;
	level: number;
	tier: string;
	candyUsed: number;
	/** @nullable */
	heldItem?: string | null;
	/** @nullable */
	skin?: string | null;
	[key: string]: unknown;
}
