/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ItemAttributesRunes } from './ItemAttributesRunes';
import type { ItemEffectAttribute } from './ItemEffectAttribute';
import type { ItemSoulAttribute } from './ItemSoulAttribute';
import type { ItemAttributesHook } from './ItemAttributesHook';
import type { ItemAttributesLine } from './ItemAttributesLine';
import type { ItemAttributesSinker } from './ItemAttributesSinker';
import type { ItemAttributesInventoryData } from './ItemAttributesInventoryData';

export interface ItemAttributes {
	/** @nullable */
	runes?: ItemAttributesRunes;
	/** @nullable */
	effects?: ItemEffectAttribute[] | null;
	/** @nullable */
	necromancer_souls?: ItemSoulAttribute[] | null;
	/** @nullable */
	hook?: ItemAttributesHook;
	/** @nullable */
	line?: ItemAttributesLine;
	/** @nullable */
	sinker?: ItemAttributesSinker;
	/** @nullable */
	ability_scroll?: string[] | null;
	/** @nullable */
	inventory_data?: ItemAttributesInventoryData;
	[key: string]: unknown;
}
