/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndInt32 } from './DictionaryOfStringAndInt32';
import type { DictionaryOfStringAndString } from './DictionaryOfStringAndString';
import type { ItemAttributes } from './ItemAttributes';
import type { ItemPetInfoDto } from './ItemPetInfoDto';
import type { ListOfString } from './ListOfString';

export interface ItemDto {
	/** Old Minecraft id of the item */
	id: number;
	/** Minecraft stack count of the item */
	count: number;
	/** Minecraft damage value of the item */
	damage: number;
	/**
	 * Skyblock ID of the item
	 * @nullable
	 */
	skyblockId?: string | null;
	/**
	 * Item UUID to uniquely identify a specific instance of this item
	 * @nullable
	 */
	uuid?: string | null;
	/**
	 * Item name, first line of the lore
	 * @nullable
	 */
	name?: string | null;
	lore?: ListOfString | null;
	enchantments?: DictionaryOfStringAndInt32 | null;
	attributes?: ItemAttributes | null;
	itemAttributes?: DictionaryOfStringAndString | null;
	gems?: DictionaryOfStringAndString | null;
	petInfo?: ItemPetInfoDto | null;
	/**
	 * Image url for the item
	 * @nullable
	 */
	imageUrl?: string | null;
	/**
	 * Texture id for the item, used to look up the image in our image service
	 * @nullable
	 */
	textureId?: string | null;
	/**
	 * Slot identifier where the item was located, if applicable
	 * @nullable
	 */
	slot?: string | null;
}
