/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface ItemSoulAttribute {
	/** @nullable */
	mob_id?: string | null;
	/** @nullable */
	dropped_instance_id?: string | null;
	/** @nullable */
	dropped_mode_id?: string | null;
}
