/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

/**
 * Applied enchantments with their levels
 * @nullable
 */
export type ItemDtoEnchantments = { [key: string]: number } | null;
