/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ItemResponseSkin } from './ItemResponseSkin';
import type { ItemGemstoneSlot } from './ItemGemstoneSlot';
import type { ItemRequirement } from './ItemRequirement';
import type { ItemResponseMuseumData } from './ItemResponseMuseumData';
import type { ItemResponseStats } from './ItemResponseStats';
import type { ItemResponseDungeonItemConversionCost } from './ItemResponseDungeonItemConversionCost';
import type { UpgradeCosts } from './UpgradeCosts';
import type { CatacombsRequirements } from './CatacombsRequirements';
import type { ItemResponseItemSpecific } from './ItemResponseItemSpecific';

export interface ItemResponse {
	/** @nullable */
	id?: string | null;
	/** @nullable */
	material?: string | null;
	/** @nullable */
	color?: string | null;
	durability: number;
	/** @nullable */
	skin?: ItemResponseSkin;
	/** @nullable */
	name?: string | null;
	/** @nullable */
	category?: string | null;
	/** @nullable */
	tier?: string | null;
	unstackable: boolean;
	glowing: boolean;
	npc_sell_price: number;
	can_auction: boolean;
	can_trade: boolean;
	can_place: boolean;
	/** @nullable */
	gemstone_slots?: ItemGemstoneSlot[] | null;
	/** @nullable */
	requirements?: ItemRequirement[] | null;
	museum: boolean;
	/** @nullable */
	museum_data?: ItemResponseMuseumData;
	/** @nullable */
	stats?: ItemResponseStats;
	generator_tier: number;
	/** @nullable */
	dungeon_item_conversion_cost?: ItemResponseDungeonItemConversionCost;
	/** @nullable */
	upgrade_costs?: UpgradeCosts[][] | null;
	/** @nullable */
	catacombs_requirements?: CatacombsRequirements[] | null;
	hide_from_viewrecipe_command: boolean;
	salvagable_from_recipe: boolean;
	/** @nullable */
	item_specific?: ItemResponseItemSpecific;
	[key: string]: unknown;
}
