/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ItemMuseumDataParent } from './ItemMuseumDataParent';
import type { ItemMuseumDataArmorSetDonationXp } from './ItemMuseumDataArmorSetDonationXp';

export interface ItemMuseumData {
	donation_xp: number;
	parent: ItemMuseumDataParent;
	/** @nullable */
	type?: string | null;
	/** @nullable */
	armor_set_donation_xp?: ItemMuseumDataArmorSetDonationXp;
	/** @nullable */
	game_stage?: string | null;
	[key: string]: unknown;
}
