/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfCropAndContestMedal } from './DictionaryOfCropAndContestMedal';
import type { DictionaryOfCropAndInt64 } from './DictionaryOfCropAndInt64';
import type { DictionaryOfCropAndJacobCropStatsDto } from './DictionaryOfCropAndJacobCropStatsDto';

export interface JacobStatsDto {
	brackets: DictionaryOfCropAndContestMedal;
	personalBests: DictionaryOfCropAndInt64;
	crops: DictionaryOfCropAndJacobCropStatsDto;
}
