/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfProfileLeaderboardMemberDto } from './ListOfProfileLeaderboardMemberDto';
import type { MemberCosmeticsDto } from './MemberCosmeticsDto';

export interface LeaderboardEntryWithRankDto {
	rank: number;
	/**
	 * Player's IGN if player leaderboard
	 * @nullable
	 */
	ign?: string | null;
	/**
	 * Player's profile name if player leaderboard
	 * @nullable
	 */
	profile?: string | null;
	/** Uuid of the player or profile */
	uuid: string;
	/** Score of the entry */
	amount: number;
	removed: boolean;
	/** Initial score of the entry */
	initialAmount: number;
	/**
	 * Game mode of the entry. Classic profiles are considered default/null.
	 * @nullable
	 */
	mode?: string | null;
	members?: ListOfProfileLeaderboardMemberDto | null;
	meta?: MemberCosmeticsDto | null;
}
