/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { LeaderboardEntryDto } from './LeaderboardEntryDto';

export interface LeaderboardPositionDto {
	/** Current rank of the player (-1 if not on leaderboard) */
	rank: number;
	/** Current score of the player (0 if not on leaderboard) */
	amount: number;
	/** The starting amount of the leaderboard entry for interval based leaderboards */
	initialAmount: number;
	/** The minimum amount required to be on the leaderboard. If this is a time based leaderboard,
this score is instead required on the normal leaderboard before the player can be on the
time based leaderboard */
	minAmount: number;
	/** The starting rank of the returned upcoming players list */
	upcomingRank: number;
	/**
	 * List of upcoming players
	 * @nullable
	 */
	upcomingPlayers?: LeaderboardEntryDto[] | null;
	/**
	 * List of previous players
	 * @nullable
	 */
	previous?: LeaderboardEntryDto[] | null;
}
