/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { LeaderboardArchiveSnapshotKind } from './LeaderboardArchiveSnapshotKind';
import type { LeaderboardArchiveResult } from './LeaderboardArchiveResult';

export interface LeaderboardArchiveRunResult {
	kind: LeaderboardArchiveSnapshotKind;
	periodIdentifier: string;
	limit: number;
	overwrite: boolean;
	results: LeaderboardArchiveResult[];
	created: number;
	skipped: number;
	overwritten: number;
	failed: number;
	totalEntries: number;
}
