/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ProfileLeaderboardMemberDto } from './ProfileLeaderboardMemberDto';
import type { LeaderboardEntryDtoMeta } from './LeaderboardEntryDtoMeta';

export interface LeaderboardEntryDto {
	/**
	 * Player's IGN if player leaderboard
	 * @nullable
	 */
	ign?: string | null;
	/**
	 * Player's profile name if player leaderboard
	 * @nullable
	 */
	profile?: string | null;
	/** Uuid of the player or profile */
	uuid: string;
	/** Score of the entry */
	amount: number;
	removed: boolean;
	/** Initial score of the entry */
	initialAmount: number;
	/**
	 * Game mode of the entry. Classic profiles are considered default/null.
	 * @nullable
	 */
	mode?: string | null;
	/** @nullable */
	members?: ProfileLeaderboardMemberDto[] | null;
	/**
	 * Metadata of the entry
	 * @nullable
	 */
	meta?: LeaderboardEntryDtoMeta;
}
