/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GlassTextStyleDto } from './GlassTextStyleDto';

export interface LeaderboardStyleTextDto {
	/** @nullable */
	color?: string | null;
	/** @nullable */
	shadowColor?: string | null;
	/** @nullable */
	shadowOpacity?: number | null;
	/** @nullable */
	fontWeight?: number | null;
	glass?: GlassTextStyleDto | null;
}
