/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { LeaderboardType } from './LeaderboardType';
import type { LeaderboardScoreDataType } from './LeaderboardScoreDataType';

export interface LeaderboardInfoDto {
	/** Leaderboard title */
	title: string;
	/**
	 * Leaderboard short title
	 * @nullable
	 */
	short?: string | null;
	/**
	 * Item Id if a collection based leaderboard
	 * @nullable
	 */
	itemId?: string | null;
	/** Leaderboard category */
	category: string;
	/** If true, the leaderboard is profile based */
	profile: boolean;
	/** Minimum score required to be on the leaderboard */
	minimumScore: number;
	/** Interval type of the leaderboard */
	intervalType: LeaderboardType;
	/** Score data type of the leaderboard */
	scoreDataType: LeaderboardScoreDataType;
}
