/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { LeaderboardStyleDataDtoBackground } from './LeaderboardStyleDataDtoBackground';
import type { LeaderboardStyleDataDtoOverlay } from './LeaderboardStyleDataDtoOverlay';
import type { LeaderboardStyleDataDtoName } from './LeaderboardStyleDataDtoName';
import type { LeaderboardStyleDataDtoScore } from './LeaderboardStyleDataDtoScore';
import type { LeaderboardStyleDataDtoRank } from './LeaderboardStyleDataDtoRank';
import type { LeaderboardStyleDataDtoSubtitle } from './LeaderboardStyleDataDtoSubtitle';

export interface LeaderboardStyleDataDto {
	/** @nullable */
	background?: LeaderboardStyleDataDtoBackground;
	/** @nullable */
	overlay?: LeaderboardStyleDataDtoOverlay;
	/** @nullable */
	gradientOpacity?: number | null;
	/** @nullable */
	gradientColor?: string | null;
	/** @nullable */
	font?: string | null;
	/** @nullable */
	name?: LeaderboardStyleDataDtoName;
	/** @nullable */
	score?: LeaderboardStyleDataDtoScore;
	/** @nullable */
	rank?: LeaderboardStyleDataDtoRank;
	/** @nullable */
	subtitle?: LeaderboardStyleDataDtoSubtitle;
}
