/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { LeaderboardEntryDto } from './LeaderboardEntryDto';

export interface LeaderboardDto {
	id: string;
	title: string;
	/** @nullable */
	shortTitle?: string | null;
	/** @nullable */
	interval?: string | null;
	/** @nullable */
	firstInterval?: string | null;
	limit: number;
	offset: number;
	maxEntries: number;
	/** The minimum score required to be on the leaderboard */
	minimumScore: number;
	startsAt: bigint;
	endsAt: bigint;
	profile: boolean;
	entries: LeaderboardEntryDto[];
}
