/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { LeaderboardScoreDataType } from './LeaderboardScoreDataType';
import type { LeaderboardType } from './LeaderboardType';

export interface LeaderboardInfoDto {
	/** Leaderboard title */
	title: string;
	/**
	 * Leaderboard short title
	 * @nullable
	 */
	short?: string | null;
	/**
	 * Item id used for the leaderboard image
	 * @nullable
	 */
	itemId?: string | null;
	/**
	 * Collection item id if this is a collection leaderboard
	 * @nullable
	 */
	collection?: string | null;
	/** Leaderboard category */
	category: string;
	/** If true, the leaderboard is profile based */
	profile: boolean;
	/** Minimum score required to be on the leaderboard */
	minimumScore: number;
	/** Amount of top ranks cached in Redis for this leaderboard. */
	cachedRankAmount: number;
	intervalType: LeaderboardType;
	scoreDataType: LeaderboardScoreDataType;
}
