/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

/**
 * Interval type of the leaderboard
 */
export type LeaderboardType = (typeof LeaderboardType)[keyof typeof LeaderboardType];

export const LeaderboardType = {
	Current: 0,
	Weekly: 1,
	Monthly: 2,
} as const;
