/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GreenhouseAccountInput } from './GreenhouseAccountInput';
import type { GreenhouseMarketInput } from './GreenhouseMarketInput';
import type { ListOfDouble } from './ListOfDouble';
import type { ListOfGreenhouseHarvestSetupInput } from './ListOfGreenhouseHarvestSetupInput';

export interface ListGreenhouseProfitsRequest {
	catalogVersion: string;
	account: GreenhouseAccountInput;
	harvestSetupCandidates: ListOfGreenhouseHarvestSetupInput;
	market: GreenhouseMarketInput;
	uniqueCropsPerPlot: number;
	/**
	 * Optional exact greenhouse-wide number of distinct unique-crop groups that every
	 *             generated layout must physically contain. When supplied, this global domain
	 *             replaces UniqueCropsPerPlot; omit it to preserve the literal
	 *             per-plot requirement.
	 * @nullable
	 */
	uniqueCropsGrown?: number | null;
	/**
	 * Optional number of greenhouse growth stages between complete player visits.
	 *             A visit discharges every surviving Thunderling before waking sleeping plants,
	 *             harvesting ready targets, and watering plants below the maintenance threshold.
	 *             Omit to retain the legacy continuous/special-case ranking policy.
	 * @nullable
	 */
	visitIntervalGrowthStages?: number | null;
	chorusHarvestsPerDay: number;
	chorusHarvestHours: ListOfDouble;
}
