/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ManagedResourcePackVersionStatus } from './ManagedResourcePackVersionStatus';

export interface ManagedResourcePackVersionDto {
	versionId: string;
	versionNumber: string;
	versionName: string;
	/** @nullable */
	previewPackId?: string | null;
	primaryFileName: string;
	primaryFileUrl: string;
	versionType: string;
	publishedAt: string;
	downloadedAt: string;
	primaryFileSize: bigint;
	/** @nullable */
	sha512?: string | null;
	/** @nullable */
	packId?: string | null;
	/** @nullable */
	packVersion?: string | null;
	/** @nullable */
	packName?: string | null;
	/** @nullable */
	packDescription?: string | null;
	packAuthors: string[];
	gameVersions: string[];
	loaders: string[];
	supportsCit: boolean;
	/** @nullable */
	packFormat?: number | null;
	validationSucceeded: boolean;
	/** @nullable */
	validationMessage?: string | null;
	status: ManagedResourcePackVersionStatus;
	/** @nullable */
	downloadedByAccountId?: string | null;
	/** @nullable */
	submittedByAccountId?: string | null;
	/** @nullable */
	submittedAt?: string | null;
	/** @nullable */
	submissionNotes?: string | null;
	/** @nullable */
	approvedByAccountId?: string | null;
	/** @nullable */
	approvedAt?: string | null;
	/** @nullable */
	rejectedByAccountId?: string | null;
	/** @nullable */
	rejectedAt?: string | null;
	/** @nullable */
	rejectionReason?: string | null;
}
