/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { MemberFortuneSettingsDtoAttributes } from './MemberFortuneSettingsDtoAttributes';
import type { MemberFortuneSettingsDtoExported } from './MemberFortuneSettingsDtoExported';

export interface MemberFortuneSettingsDto {
	/** Amount of strength used for mooshroom fortune */
	strength: number;
	/** Community center farming fortune level */
	communityCenter: number;
	/** Attribute shards */
	attributes: MemberFortuneSettingsDtoAttributes;
	/** Exported crops */
	exported: MemberFortuneSettingsDtoExported;
}
