/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndInt32 } from './DictionaryOfStringAndInt32';
import type { DictionaryOfStringAndString } from './DictionaryOfStringAndString';

export interface MemberFortuneSettingsDto {
	/** Amount of strength used for mooshroom fortune */
	strength: number;
	/** Community center farming fortune level */
	communityCenter: number;
	/** Consumed Filled Rosewater Flasks */
	rosewaterFlasks: number;
	attributes: DictionaryOfStringAndInt32;
	chipRarities: DictionaryOfStringAndString;
}
