/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { MemberFortuneSettingsDtoAttributes } from './MemberFortuneSettingsDtoAttributes';
import type { MemberFortuneSettingsDtoChipRarities } from './MemberFortuneSettingsDtoChipRarities';

export interface MemberFortuneSettingsDto {
	/** Amount of strength used for mooshroom fortune */
	strength: number;
	/** Community center farming fortune level */
	communityCenter: number;
	/** Consumed Filled Rosewater Flasks */
	rosewaterFlasks: number;
	/** Attribute shards */
	attributes: MemberFortuneSettingsDtoAttributes;
	/** User-provided Garden Chip rarity assumptions. API data only exposes chip levels. */
	chipRarities: MemberFortuneSettingsDtoChipRarities;
}
