/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

/**
 * Generic milestone progress wrapper for Rock/Dolphin pet milestones.
 */
export interface MilestoneProgressDto {
	/**
	 * Current rarity tier (null when below the first milestone).
	 * @nullable
	 */
	currentRarity?: string | null;
	/** Required progress for the current rarity (0 when below the first milestone). */
	currentRequired: number;
	/**
	 * Next rarity tier (null when at max).
	 * @nullable
	 */
	nextRarity?: string | null;
	/**
	 * Required progress to reach the next rarity (null when at max).
	 * @nullable
	 */
	nextRequired?: number | null;
	/** Current raw progress count. */
	progress: number;
	/** Progress towards the next milestone (0-1). 1.0 when at max rarity. */
	percent: number;
}
