/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { UserSettingsDto } from './UserSettingsDto';
import type { MinecraftSkinDto } from './MinecraftSkinDto';
import type { ProfileDetailsDto } from './ProfileDetailsDto';
import type { UserBadgeDto } from './UserBadgeDto';
import type { MinecraftAccountDtoPlayerData } from './MinecraftAccountDtoPlayerData';

export interface MinecraftAccountDto {
	id: string;
	name: string;
	formattedName: string;
	primaryAccount: boolean;
	/** @nullable */
	discordId?: string | null;
	/** @nullable */
	discordUsername?: string | null;
	/** @nullable */
	discordAvatar?: string | null;
	settings: UserSettingsDto;
	skin: MinecraftSkinDto;
	profiles: ProfileDetailsDto[];
	badges: UserBadgeDto[];
	/** @nullable */
	playerData?: MinecraftAccountDtoPlayerData;
}
