/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { MilestoneProgressDto } from './MilestoneProgressDto';

/**
 * Derived Rock pet milestone progress (driven by player_stats.pets.milestones.ores_mined).
 * @nullable
 */
export type MiningStatsDtoRockMilestone = MilestoneProgressDto | null;
