/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndInt32 } from './DictionaryOfStringAndInt32';
import type { FestivalStatsDto } from './FestivalStatsDto';
import type { ListOfPetScoreRewardDto } from './ListOfPetScoreRewardDto';

export interface MiscStatsDto {
	essence: DictionaryOfStringAndInt32;
	dragonsSacrificed: number;
	firstJoin: bigint;
	firstJoinHub: bigint;
	skyblockLevel: number;
	skyblockProgress: number;
	soulflow: bigint;
	/** @nullable */
	favoriteArrow?: string | null;
	refinedJyrreUses: number;
	pelts: number;
	levelingCompletions: DictionaryOfStringAndInt32;
	highestPetScore: number;
	unlockedPetScoreRewards: ListOfPetScoreRewardDto;
	festivals: FestivalStatsDto;
}
