/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { NameCardStyleDataDecal } from './NameCardStyleDataDecal';
import type { WeightStyleBackground } from './WeightStyleBackground';
import type { NameCardStyleElements } from './NameCardStyleElements';
import type { WeightStyleGradient } from './WeightStyleGradient';
import type { NameCardRankAnchor } from './NameCardRankAnchor';

export interface NameCardStyleData {
	/** @nullable */
	decal?: NameCardStyleDataDecal;
	/** @nullable */
	gradients?: WeightStyleGradient[] | null;
	background: WeightStyleBackground;
	elements: NameCardStyleElements;
	/** @nullable */
	rankAnchor?: NameCardRankAnchor | null;
}
