/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfWeightStyleGradient } from './ListOfWeightStyleGradient';
import type { NameCardLayout } from './NameCardLayout';
import type { NameCardRankAnchor } from './NameCardRankAnchor';
import type { NameCardStyleElements } from './NameCardStyleElements';
import type { WeightStyleBackground } from './WeightStyleBackground';
import type { WeightStyleDecal } from './WeightStyleDecal';

export interface NameCardStyleData {
	layout?: NameCardLayout | null;
	decal?: WeightStyleDecal | null;
	gradients?: ListOfWeightStyleGradient | null;
	background: WeightStyleBackground;
	elements: NameCardStyleElements;
	rankAnchor?: NameCardRankAnchor | null;
}
