/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { NameCardStyleElementsDtoAvatar } from './NameCardStyleElementsDtoAvatar';
import type { NameCardStyleElementsDtoName } from './NameCardStyleElementsDtoName';
import type { NameCardStyleElementsDtoRank } from './NameCardStyleElementsDtoRank';
import type { NameCardStyleElementsDtoWeight } from './NameCardStyleElementsDtoWeight';
import type { NameCardStyleElementsDtoLabel } from './NameCardStyleElementsDtoLabel';

export interface NameCardStyleElementsDto {
	/** @nullable */
	avatar?: NameCardStyleElementsDtoAvatar;
	/** @nullable */
	name?: NameCardStyleElementsDtoName;
	/** @nullable */
	rank?: NameCardStyleElementsDtoRank;
	/** @nullable */
	weight?: NameCardStyleElementsDtoWeight;
	/** @nullable */
	label?: NameCardStyleElementsDtoLabel;
}
