/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfWeightStyleGradientDto } from './ListOfWeightStyleGradientDto';
import type { NameCardRankAnchorDto } from './NameCardRankAnchorDto';
import type { NameCardStyleElementsDto } from './NameCardStyleElementsDto';
import type { WeightStyleBackgroundDto } from './WeightStyleBackgroundDto';
import type { WeightStyleDecalDto } from './WeightStyleDecalDto';

export interface NameCardStyleDataDto {
	decal?: WeightStyleDecalDto | null;
	gradients?: ListOfWeightStyleGradientDto | null;
	background: WeightStyleBackgroundDto;
	elements: NameCardStyleElementsDto;
	rankAnchor?: NameCardRankAnchorDto | null;
}
