/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { NetworthItemAttributesRunes } from './NetworthItemAttributesRunes';
import type { NetworthItemEffectAttribute } from './NetworthItemEffectAttribute';
import type { NetworthItemSoulAttribute } from './NetworthItemSoulAttribute';
import type { NetworthItemAttributesHook } from './NetworthItemAttributesHook';
import type { NetworthItemAttributesLine } from './NetworthItemAttributesLine';
import type { NetworthItemAttributesSinker } from './NetworthItemAttributesSinker';
import type { NetworthItemAttributesInventory } from './NetworthItemAttributesInventory';
import type { NetworthItemAttributesExtra } from './NetworthItemAttributesExtra';

export interface NetworthItemAttributes {
	/** @nullable */
	runes?: NetworthItemAttributesRunes;
	/** @nullable */
	effects?: NetworthItemEffectAttribute[] | null;
	/** @nullable */
	necromancerSouls?: NetworthItemSoulAttribute[] | null;
	/** @nullable */
	hook?: NetworthItemAttributesHook;
	/** @nullable */
	line?: NetworthItemAttributesLine;
	/** @nullable */
	sinker?: NetworthItemAttributesSinker;
	/** @nullable */
	abilityScrolls?: string[] | null;
	/** @nullable */
	inventory?: NetworthItemAttributesInventory;
	extra: NetworthItemAttributesExtra;
}
