/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { NetworthBreakdownCategories } from './NetworthBreakdownCategories';

export interface NetworthBreakdown {
	networth: number;
	liquidNetworth: number;
	functionalNetworth: number;
	liquidFunctionalNetworth: number;
	purse: number;
	bank: number;
	personalBank: number;
	categories: NetworthBreakdownCategories;
}
