/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndObject } from './DictionaryOfStringAndObject';
import type { NotificationType } from './NotificationType';

export interface NotificationDto {
	id: bigint;
	type: NotificationType;
	title: string;
	/** @nullable */
	message?: string | null;
	/** @nullable */
	plainMessage?: string | null;
	/** @nullable */
	link?: string | null;
	isRead: boolean;
	createdAt: string;
	data?: DictionaryOfStringAndObject | null;
}
