/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationType = {
	system: 'system',
	guideApproved: 'guideApproved',
	guideEditApproved: 'guideEditApproved',
	guideRejected: 'guideRejected',
	guideDeleted: 'guideDeleted',
	commentApproved: 'commentApproved',
	commentEditApproved: 'commentEditApproved',
	commentRejected: 'commentRejected',
	newComment: 'newComment',
	newReply: 'newReply',
	shopPurchase: 'shopPurchase',
	guideSubmitted: 'guideSubmitted',
} as const;
