/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];

export const NotificationType = {
	system: 'system',
	guideApproved: 'guideApproved',
	guideEditApproved: 'guideEditApproved',
	guideRejected: 'guideRejected',
	guideDeleted: 'guideDeleted',
	commentApproved: 'commentApproved',
	commentEditApproved: 'commentEditApproved',
	commentRejected: 'commentRejected',
	newComment: 'newComment',
	newReply: 'newReply',
	shopPurchase: 'shopPurchase',
	guideSubmitted: 'guideSubmitted',
	shopRefund: 'shopRefund',
	giftReceived: 'giftReceived',
	giftReassignable: 'giftReassignable',
	giftClaimed: 'giftClaimed',
	dataExportReady: 'dataExportReady',
	badgeUnlocked: 'badgeUnlocked',
	managedPackApproved: 'managedPackApproved',
	managedPackOwnershipAssigned: 'managedPackOwnershipAssigned',
	auctionSold: 'auctionSold',
	feedbackSubmitted: 'feedbackSubmitted',
	feedbackApproved: 'feedbackApproved',
	feedbackRejected: 'feedbackRejected',
	feedbackStatusChanged: 'feedbackStatusChanged',
	feedbackMerged: 'feedbackMerged',
	feedbackUpdate: 'feedbackUpdate',
	bugReportReply: 'bugReportReply',
	bugReportNeedsInformation: 'bugReportNeedsInformation',
	bugReportLinked: 'bugReportLinked',
	bugReportStatusChanged: 'bugReportStatusChanged',
	feedbackDeleted: 'feedbackDeleted',
} as const;
