/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { GiftItemDto } from './GiftItemDto';

/**
 * Summary of a pending gift order that the authenticated user can claim.
 */
export interface PendingGiftDto {
	orderId: string;
	buyerId: string;
	buyerName: string;
	provider: string;
	orderDate: string;
	/** @nullable */
	completedAt?: string | null;
	/** @nullable */
	claimExpiresAt?: string | null;
	/** @nullable */
	giftMessage?: string | null;
	items: GiftItemDto[];
}
