/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type Pest = (typeof Pest)[keyof typeof Pest];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Pest = {
	Mite: 0,
	Cricket: 1,
	Moth: 2,
	Earthworm: 3,
	Slug: 4,
	Beetle: 5,
	Locust: 6,
	Rat: 7,
	Mosquito: 8,
	Fly: 9,
	Mouse: 10,
} as const;
