/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export interface PetDto {
	/** @nullable */
	uuid?: string | null;
	/** @nullable */
	localId?: string | null;
	type: string;
	exp: number;
	active: boolean;
	/** @nullable */
	tier?: string | null;
	/** @nullable */
	heldItem?: string | null;
	candyUsed: number;
	/** @nullable */
	skin?: string | null;
	level: number;
	maxLevel: number;
	progress: number;
	xpCurrent: number;
	xpForNext: number;
	xpMaxLevel: number;
}
