/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { ListOfKillEntryDto } from './ListOfKillEntryDto';

/**
 * Aggregated derivations over KillsDeaths dictionaries: top kills/deaths,
 *             totals, K/D ratio, and notable boss-mob counts.
 */
export interface PlayerStatsDerivationsDto {
	totalKills: number;
	totalDeaths: number;
	killDeathRatio: number;
	topKills: ListOfKillEntryDto;
	topDeaths: ListOfKillEntryDto;
	notableBossKills: DictionaryOfStringAndDouble;
}
