/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuctionStatsData } from './AuctionStatsData';
import type { DamageStatsDto } from './DamageStatsDto';
import type { DictionaryOfStringAndDouble } from './DictionaryOfStringAndDouble';
import type { DictionaryOfStringAndJsonElement } from './DictionaryOfStringAndJsonElement';
import type { DragonFightData } from './DragonFightData';
import type { FairySoulsDto } from './FairySoulsDto';
import type { GiftsDto } from './GiftsDto';
import type { KillsDeathsDto } from './KillsDeathsDto';
import type { MythosData } from './MythosData';
import type { PlayerStatsDerivationsDto } from './PlayerStatsDerivationsDto';

export interface PlayerStatsDto {
	fairySouls: FairySoulsDto;
	killsDeaths: KillsDeathsDto;
	damage: DamageStatsDto;
	gifts: GiftsDto;
	glowingMushroomsBroken: number;
	mythos?: MythosData | null;
	spooky?: DictionaryOfStringAndJsonElement | null;
	winter?: DictionaryOfStringAndDouble | null;
	petMilestones?: DictionaryOfStringAndDouble | null;
	dragonFight?: DragonFightData | null;
	auctions?: AuctionStatsData | null;
	derivations?: PlayerStatsDerivationsDto | null;
}
