/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { FairySoulsDto } from './FairySoulsDto';
import type { KillsDeathsDto } from './KillsDeathsDto';
import type { DamageStatsDto } from './DamageStatsDto';
import type { GiftsDto } from './GiftsDto';
import type { PlayerStatsDtoMythos } from './PlayerStatsDtoMythos';
import type { PlayerStatsDtoSpooky } from './PlayerStatsDtoSpooky';
import type { PlayerStatsDtoWinter } from './PlayerStatsDtoWinter';
import type { PlayerStatsDtoPetMilestones } from './PlayerStatsDtoPetMilestones';
import type { PlayerStatsDtoDragonFight } from './PlayerStatsDtoDragonFight';
import type { PlayerStatsDtoAuctions } from './PlayerStatsDtoAuctions';
import type { PlayerStatsDtoDerivations } from './PlayerStatsDtoDerivations';

export interface PlayerStatsDto {
	fairySouls: FairySoulsDto;
	killsDeaths: KillsDeathsDto;
	damage: DamageStatsDto;
	gifts: GiftsDto;
	glowingMushroomsBroken: number;
	/** @nullable */
	mythos?: PlayerStatsDtoMythos;
	/** @nullable */
	spooky?: PlayerStatsDtoSpooky;
	/** @nullable */
	winter?: PlayerStatsDtoWinter;
	/** @nullable */
	petMilestones?: PlayerStatsDtoPetMilestones;
	/** @nullable */
	dragonFight?: PlayerStatsDtoDragonFight;
	/** @nullable */
	auctions?: PlayerStatsDtoAuctions;
	/**
   * Aggregated derivations over KillsDeaths dictionaries: top kills/deaths,
totals, K/D ratio, and notable boss-mob counts.
   * @nullable
   */
	derivations?: PlayerStatsDtoDerivations;
}
