/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { KillEntryDto } from './KillEntryDto';
import type { PlayerStatsDerivationsDtoNotableBossKills } from './PlayerStatsDerivationsDtoNotableBossKills';

/**
 * Aggregated player-stat derivations: top kills/deaths, totals, K/D, and notable boss kill
counts pulled from the player_stats.kills dictionary by canonical mob id.
 */
export interface PlayerStatsDerivationsDto {
	totalKills: number;
	totalDeaths: number;
	killDeathRatio: number;
	topKills: KillEntryDto[];
	topDeaths: KillEntryDto[];
	/** Counts for well-known SkyBlock boss/event mobs. Entries are only present when the kill
count is greater than zero. Includes endstone_protector (End Island), Crystal
Hollows boss corleone, Mythological event gaia_construct/minos_*,
Halloween headless_horseman, Season-of-Jerry jerry_pony/nutcracker,
and others. */
	notableBossKills: PlayerStatsDerivationsDtoNotableBossKills;
}
