/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { PlayerDataDtoGuildMember } from './PlayerDataDtoGuildMember';
import type { PlayerDataDtoSocialMedia } from './PlayerDataDtoSocialMedia';

export interface PlayerDataDto {
	uuid: string;
	/** @nullable */
	displayname?: string | null;
	firstLogin: bigint;
	lastLogin: bigint;
	lastLogout: bigint;
	karma: bigint;
	networkExp: number;
	/** @nullable */
	guildMember?: PlayerDataDtoGuildMember;
	rewardHighScore: number;
	rewardScore: number;
	rewardStreak: number;
	totalDailyRewards: number;
	totalRewards: number;
	/** @nullable */
	prefix?: string | null;
	/** @nullable */
	rank?: string | null;
	/** @nullable */
	packageRank?: string | null;
	/** @nullable */
	newPackageRank?: string | null;
	/** @nullable */
	rankPlusColor?: string | null;
	/** @nullable */
	monthlyPackageRank?: string | null;
	/** @nullable */
	mostRecentMonthlyPackageRank?: string | null;
	/** @nullable */
	monthlyRankColor?: string | null;
	/** @nullable */
	socialMedia?: PlayerDataDtoSocialMedia;
}
