/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GuildFeatures } from './GuildFeatures';
import type { PrivateGuildDtoIcon } from './PrivateGuildDtoIcon';
import type { PrivateGuildDtoBanner } from './PrivateGuildDtoBanner';
import type { GuildChannelDto } from './GuildChannelDto';
import type { GuildRoleDto } from './GuildRoleDto';

export interface PrivateGuildDto {
	id: string;
	name: string;
	public: boolean;
	features: GuildFeatures;
	/** @nullable */
	icon?: PrivateGuildDtoIcon;
	/** @nullable */
	banner?: PrivateGuildDtoBanner;
	/** @nullable */
	inviteCode?: string | null;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	adminRole?: string | null;
	/** @nullable */
	botPermissions?: string | null;
	botPermissionsNew: string;
	discordFeatures: string[];
	memberCount: number;
	channels: GuildChannelDto[];
	roles: GuildRoleDto[];
}
