/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ProblemDetailsError } from './ProblemDetailsError';

/**
 * RFC7807 compatible problem details/ error response class. this can be used by configuring startup like so:
app.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 */
export interface ProblemDetails {
	type: string;
	title: string;
	status: number;
	instance: string;
	traceId: string;
	/**
	 * the details of the error
	 * @nullable
	 */
	detail?: string | null;
	errors: ProblemDetailsError[];
}
