/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ProblemDetailsErrorsItem } from './ProblemDetailsErrorsItem';

/**
 * RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:
 * ```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```
 */
export interface ProblemDetails {
	/** @nullable */
	type: string | null;
	/** @nullable */
	title: string | null;
	status: number;
	instance: string;
	traceId: string;
	/**
	 * the details of the error
	 * @nullable
	 */
	detail?: string | null;
	errors: ProblemDetailsErrorsItem[];
}
