/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

/**
 * the error details object
 */
export interface ProblemDetailsError {
	/** the name of the error or property of the dto that caused the error */
	name: string;
	/** the reason for the error */
	reason: string;
	/**
	 * the code of the error
	 * @nullable
	 */
	code?: string | null;
	/**
	 * the severity of the error
	 * @nullable
	 */
	severity?: string | null;
}
