/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ProductType } from './ProductType';
import type { UnlockedProductFeaturesDto } from './UnlockedProductFeaturesDto';
import type { WeightStyleLinkedDto } from './WeightStyleLinkedDto';
import type { ProductDtoThumbnail } from './ProductDtoThumbnail';
import type { ImageAttachmentDto } from './ImageAttachmentDto';

export interface ProductDto {
	/** Product ID */
	id: string;
	/** Product name */
	name: string;
	/** Slug of the product */
	slug: string;
	/** Product price */
	price: number;
	/**
	 * Product description
	 * @nullable
	 */
	description?: string | null;
	/** If the product is available for purchase */
	available: boolean;
	/** Type of product */
	type: ProductType;
	/** Features of the product */
	features: UnlockedProductFeaturesDto;
	/** Unlocked weight styles */
	weightStyles: WeightStyleLinkedDto[];
	/**
	 * Product thumbnail
	 * @nullable
	 */
	thumbnail?: ProductDtoThumbnail;
	/** Product Images */
	images: ImageAttachmentDto[];
	/** Discord flags */
	flags: number;
	isSubscription: boolean;
	isGuildSubscription: boolean;
	isUserSubscription: boolean;
}
