/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { EventMemberStatus } from './EventMemberStatus';

export interface ProfileEventMemberDto {
	eventId: string;
	eventName: string;
	/** @nullable */
	teamId?: string | null;
	status: EventMemberStatus;
	/** Currently not populated */
	rank: number;
	/** @nullable */
	score?: string | null;
}
