/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { ProfileBankingTransactionDto } from './ProfileBankingTransactionDto';
import type { ProfileDetailsDtoCommunityUpgrades } from './ProfileDetailsDtoCommunityUpgrades';
import type { MemberDetailsDto } from './MemberDetailsDto';

export interface ProfileDetailsDto {
	profileId: string;
	profileName: string;
	gameMode: string;
	selected: boolean;
	bankBalance: number;
	/** Recent bank transactions only. */
	bankTransactions: ProfileBankingTransactionDto[];
	/**
	 * Profile-level community upgrades state
	 * @nullable
	 */
	communityUpgrades?: ProfileDetailsDtoCommunityUpgrades;
	deleted: boolean;
	members: MemberDetailsDto[];
}
