/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export interface ProfileMemberNetworthDto {
	normal: number;
	liquid: number;
	functional: number;
	liquidFunctional: number;
	/** True when inventory API access was disabled, meaning networth is incomplete. */
	noInventory: boolean;
}
