/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { PublicGuildDtoIcon } from './PublicGuildDtoIcon';
import type { PublicGuildDtoBanner } from './PublicGuildDtoBanner';
import type { PublicGuildFeaturesDto } from './PublicGuildFeaturesDto';

export interface PublicGuildDto {
	id: string;
	name: string;
	/** @nullable */
	icon?: PublicGuildDtoIcon;
	/** @nullable */
	banner?: PublicGuildDtoBanner;
	/** @nullable */
	inviteCode?: string | null;
	/** @nullable */
	description?: string | null;
	memberCount: number;
	features: PublicGuildFeaturesDto;
}
