/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DiscordRole } from './DiscordRole';
import type { ExcludedTimespan } from './ExcludedTimespan';
import type { PublicJacobLeaderboardDto } from './PublicJacobLeaderboardDto';

export interface PublicJacobLeaderboardFeatureDto {
	maxLeaderboards: number;
	blockedRoles: DiscordRole[];
	requiredRoles: DiscordRole[];
	excludedTimespans: ExcludedTimespan[];
	leaderboards: PublicJacobLeaderboardDto[];
}
