/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { PublicGuildFeaturesDtoJacobLeaderboard } from './PublicGuildFeaturesDtoJacobLeaderboard';
import type { PublicGuildFeaturesDtoEventSettings } from './PublicGuildFeaturesDtoEventSettings';
import type { PublicGuildFeaturesDtoContestPings } from './PublicGuildFeaturesDtoContestPings';

export interface PublicGuildFeaturesDto {
	jacobLeaderboardEnabled: boolean;
	/** @nullable */
	jacobLeaderboard?: PublicGuildFeaturesDtoJacobLeaderboard;
	eventsEnabled: boolean;
	/** @nullable */
	eventSettings?: PublicGuildFeaturesDtoEventSettings;
	contestPingsEnabled: boolean;
	/** @nullable */
	contestPings?: PublicGuildFeaturesDtoContestPings;
}
