/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export interface RecentlyEndedAuctionDto {
	auctionId: string;
	sellerUuid: string;
	sellerProfileUuid: string;
	buyerUuid: string;
	buyerProfileUuid: string;
	timestamp: bigint;
	price: bigint;
	bin: boolean;
	count: number;
	/** @nullable */
	itemUuid?: string | null;
	/** @nullable */
	skyblockId?: string | null;
	variantKey: string;
	/** @nullable */
	itemBytesBase64?: string | null;
}
