/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

/**
 * Removed filter to get leaderboard entries that have been removed from the leaderboard.
 *             Default is profiles that have not been removed/wiped.
 *             0 = Not Removed
 *             1 = Removed
 *             2 = All
 */
export type RemovedFilter = (typeof RemovedFilter)[keyof typeof RemovedFilter];

export const RemovedFilter = {
	NotRemoved: 0,
	Removed: 1,
	All: 2,
} as const;
