/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type RemovedFilter = (typeof RemovedFilter)[keyof typeof RemovedFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RemovedFilter = {
	NotRemoved: 0,
	Removed: 1,
	All: 2,
} as const;
