/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

/**
 * Request to manually resolve a gift recipient.
 */
export interface ResolveRecipientRequest {
	recipientType: string;
	/** @nullable */
	minecraftUuid?: string | null;
	/** @nullable */
	guildId?: string | null;
}
