/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { IReadOnlyListOfString } from './IReadOnlyListOfString';

export interface ResourcePackDto {
	id: string;
	name: string;
	version: string;
	description: string;
	authors: IReadOnlyListOfString;
	/** @nullable */
	downloadUrl?: string | null;
	supportsCit: boolean;
	/** @nullable */
	packFormat?: number | null;
	/** @nullable */
	iconDataUrl?: string | null;
	defaultEnabled: boolean;
	/** @nullable */
	fontUrl?: string | null;
	/** @nullable */
	fontVersion?: string | null;
}
