/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfRiftSecuredTrophyDto } from './ListOfRiftSecuredTrophyDto';
import type { ListOfString } from './ListOfString';

export interface RiftStatsDto {
	/** @nullable */
	lastFreeAccess?: bigint | null;
	consumedPrism: boolean;
	motesPurse: number;
	lifetimeMotesEarned: bigint;
	motesOrbPickup: number;
	visits: number;
	foundCats: ListOfString;
	unlockedRiftCatPet: boolean;
	enigmaSoulsFound: number;
	enigmaSoulsTotal: number;
	securedVisitors: ListOfString;
	securedTrophies: ListOfRiftSecuredTrophyDto;
	grubberStacks: number;
	maxBurgers: number;
	unlockedEyes: ListOfString;
	totalPortals: number;
	lifetimePurchasedBoundaries: ListOfString;
	croakStacks: number;
	sirenStatueKills: number;
}
