/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

/**
 * Pre-built typed view of common Season-of-Jerry counters extracted from the loosely-typed
player_stats.winter dictionary. Both standard SkyBlock keys and the older
winter_ prefixed variants are recognised.
 */
export interface SeasonOfJerryStatsDto {
	cannonballsHit: number;
	snowballsHit: number;
	damageDealt: number;
	magmaDamageDealt: number;
	giftsGiven: number;
	giftsReceived: number;
	jerryBoxesOpened: number;
	mostSnowballsHit: number;
	mostCannonballsHit: number;
	mostDamageDealt: number;
	mostMagmaDamageDealt: number;
}
