/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuthorDto } from './AuthorDto';
import type { ImageAttachmentDto } from './ImageAttachmentDto';
import type { ListOfProductDto } from './ListOfProductDto';

export interface ShopCategoryDto {
	id: number;
	title: string;
	slug: string;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	longDescription?: string | null;
	bannerImage?: ImageAttachmentDto | null;
	assignedArtist?: AuthorDto | null;
	order: number;
	published: boolean;
	products: ListOfProductDto;
}
