/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export interface SkillsDto {
	farming: number;
	mining: number;
	combat: number;
	foraging: number;
	fishing: number;
	enchanting: number;
	alchemy: number;
	carpentry: number;
	runecrafting: number;
	taming: number;
	social: number;
	hunting: number;
}
