/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { SkyblockItemResponseData } from './SkyblockItemResponseData';
import type { SkyblockItemResponseBazaar } from './SkyblockItemResponseBazaar';
import type { AuctionItemDto } from './AuctionItemDto';

export interface SkyblockItemResponse {
	itemId: string;
	/** @nullable */
	name?: string | null;
	/**
	 * Data from the Hypixel items endpoint
	 * @nullable
	 */
	data?: SkyblockItemResponseData;
	/** @nullable */
	bazaar?: SkyblockItemResponseBazaar;
	/** @nullable */
	auctions?: AuctionItemDto[] | null;
}
