/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DictionaryOfInt32AndInt32 } from './DictionaryOfInt32AndInt32';
import type { DictionaryOfStringAndBoolean } from './DictionaryOfStringAndBoolean';

export interface SlayerBossData {
	xp: bigint;
	level: number;
	maxLevel: number;
	progress: number;
	xpForNext: bigint;
	claimedLevels: DictionaryOfStringAndBoolean;
	bossKills: DictionaryOfInt32AndInt32;
	bossAttempts: DictionaryOfInt32AndInt32;
}
