/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { TebexUserOrderStateDtoCheckoutLinks } from './TebexUserOrderStateDtoCheckoutLinks';
import type { TebexUserOrderStateDtoLastWebhook } from './TebexUserOrderStateDtoLastWebhook';
import type { TebexUserOrderStateDtoBasket } from './TebexUserOrderStateDtoBasket';
import type { TebexUserOrderStateDtoPriceDetails } from './TebexUserOrderStateDtoPriceDetails';
import type { TebexUserOrderStateDtoBasketMismatch } from './TebexUserOrderStateDtoBasketMismatch';
import type { TebexUserOrderStateDtoPayment } from './TebexUserOrderStateDtoPayment';
import type { TebexUserOrderStateDtoRecurring } from './TebexUserOrderStateDtoRecurring';

export interface TebexUserOrderStateDto {
	/** @nullable */
	basketIdent?: string | null;
	/** @nullable */
	basketUrl?: string | null;
	/** @nullable */
	checkoutLinks?: TebexUserOrderStateDtoCheckoutLinks;
	/** @nullable */
	recurringReference?: string | null;
	/** @nullable */
	providerStatus?: string | null;
	/** @nullable */
	lastSyncedAt?: string | null;
	/** @nullable */
	lastWebhook?: TebexUserOrderStateDtoLastWebhook;
	/** @nullable */
	basket?: TebexUserOrderStateDtoBasket;
	/** @nullable */
	expiresAt?: string | null;
	/** @nullable */
	priceDetails?: TebexUserOrderStateDtoPriceDetails;
	/** @nullable */
	lastErrorCode?: string | null;
	/** @nullable */
	basketMismatch?: TebexUserOrderStateDtoBasketMismatch;
	/** @nullable */
	payment?: TebexUserOrderStateDtoPayment;
	/** @nullable */
	recurring?: TebexUserOrderStateDtoRecurring;
}
