/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export interface TebexUserBasketRowDto {
	/** @nullable */
	rowId?: number | null;
	/** @nullable */
	orderItemId?: string | null;
	/** @nullable */
	productId?: string | null;
	/** @nullable */
	type?: string | null;
	quantity: number;
	/** @nullable */
	unitPrice?: number | null;
	/** @nullable */
	totalPrice?: number | null;
	/** @nullable */
	name?: string | null;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	imageUrl?: string | null;
}
