/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */

export interface TebexCheckoutResponseDto {
	orderId: string;
	provider: string;
	status: string;
	/** @nullable */
	checkoutIdent?: string | null;
	/** @nullable */
	checkoutUrl?: string | null;
	/** @nullable */
	authUrl?: string | null;
	/** @nullable */
	currency?: string | null;
	/** @nullable */
	totalPrice?: number | null;
	/** @nullable */
	expiresAt?: string | null;
}
