/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { TebexExpectedBasketItem } from './TebexExpectedBasketItem';

export interface TebexBasketMismatchSnapshot {
	/** @nullable */
	reason?: string | null;
	expectedItems: TebexExpectedBasketItem[];
	receivedItems: TebexExpectedBasketItem[];
	/** @nullable */
	expectedAmount?: number | null;
	/** @nullable */
	receivedAmount?: number | null;
	/** @nullable */
	receivedBasketIdent?: string | null;
}
