/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { TebexAdminPaymentStateDto } from './TebexAdminPaymentStateDto';
import type { TebexAdminRecurringStateDto } from './TebexAdminRecurringStateDto';
import type { TebexBasketMismatchSnapshot } from './TebexBasketMismatchSnapshot';
import type { TebexPriceDetailsSnapshot } from './TebexPriceDetailsSnapshot';
import type { TebexUserBasketDto } from './TebexUserBasketDto';
import type { TebexUserCheckoutLinksDto } from './TebexUserCheckoutLinksDto';
import type { TebexWebhookSummary } from './TebexWebhookSummary';

export interface TebexUserOrderStateDto {
	/** @nullable */
	basketIdent?: string | null;
	/** @nullable */
	basketUrl?: string | null;
	checkoutLinks?: TebexUserCheckoutLinksDto | null;
	/** @nullable */
	recurringReference?: string | null;
	/** @nullable */
	providerStatus?: string | null;
	/** @nullable */
	lastSyncedAt?: string | null;
	lastWebhook?: TebexWebhookSummary | null;
	basket?: TebexUserBasketDto | null;
	/** @nullable */
	expiresAt?: string | null;
	priceDetails?: TebexPriceDetailsSnapshot | null;
	/** @nullable */
	lastErrorCode?: string | null;
	basketMismatch?: TebexBasketMismatchSnapshot | null;
	payment?: TebexAdminPaymentStateDto | null;
	recurring?: TebexAdminRecurringStateDto | null;
}
