/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { TebexAdminPaymentStateDto } from './TebexAdminPaymentStateDto';
import type { TebexAdminRecurringStateDto } from './TebexAdminRecurringStateDto';
import type { TebexBasketMismatchSnapshot } from './TebexBasketMismatchSnapshot';
import type { TebexExpectedBasketSnapshot } from './TebexExpectedBasketSnapshot';
import type { TebexOrderSnapshot } from './TebexOrderSnapshot';

export interface TebexAdminOrderDetailDto {
	/** @nullable */
	basketIdent?: string | null;
	/** @nullable */
	basketUrl?: string | null;
	/** @nullable */
	recurringReference?: string | null;
	/** @nullable */
	providerStatus?: string | null;
	/** @nullable */
	lastSyncedAt?: string | null;
	expectedBasket?: TebexExpectedBasketSnapshot | null;
	orderSnapshot?: TebexOrderSnapshot | null;
	basketMismatch?: TebexBasketMismatchSnapshot | null;
	payment?: TebexAdminPaymentStateDto | null;
	recurring?: TebexAdminRecurringStateDto | null;
}
