/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { TebexUserBasketDtoPriceDetails } from './TebexUserBasketDtoPriceDetails';
import type { TebexUserBasketRowDto } from './TebexUserBasketRowDto';

export interface TebexUserBasketDto {
	/** @nullable */
	ident?: string | null;
	/** @nullable */
	creatorCode?: string | null;
	/** @nullable */
	country?: string | null;
	paymentStarted: boolean;
	/** @nullable */
	expiresAt?: string | null;
	/** @nullable */
	price?: number | null;
	/** @nullable */
	priceDetails?: TebexUserBasketDtoPriceDetails;
	rows: TebexUserBasketRowDto[];
}
