/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { TebexPackageSnapshotCategory } from './TebexPackageSnapshotCategory';

export interface TebexPackageSnapshot {
	id: number;
	name: string;
	/** @nullable */
	slug?: string | null;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	type?: string | null;
	basePrice: number;
	/** @nullable */
	salesPrice?: number | null;
	/** @nullable */
	totalPrice?: number | null;
	/** @nullable */
	currency?: string | null;
	/** @nullable */
	category?: TebexPackageSnapshotCategory;
	/** @nullable */
	image?: string | null;
}
