/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { TebexProductConfigVariableData } from './TebexProductConfigVariableData';

export interface TebexProductConfig {
	allowGiftUser: boolean;
	allowGiftGuild: boolean;
	creatorCodeAllowed: boolean;
	requiresMinecraftIdentity: boolean;
	/** @nullable */
	defaultCreatorCode?: string | null;
	/** @nullable */
	checkoutNameOverride?: string | null;
	/** @nullable */
	checkoutDescriptionOverride?: string | null;
	/** @nullable */
	imageUrlOverride?: string | null;
	/** @nullable */
	billingType?: string | null;
	/** @nullable */
	billingPeriod?: string | null;
	/** @nullable */
	billingFrequency?: number | null;
	/** @nullable */
	variableData?: TebexProductConfigVariableData;
}
