/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { TebexProductConfig } from './TebexProductConfig';

/**
 * Tebex-specific checkout settings for the product
 */
export interface TebexProductSettingsDto {
	id: string;
	productId: bigint;
	enabled: boolean;
	supportsGifting: boolean;
	config?: TebexProductConfig | null;
}
