/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { TebexBasketSnapshotPriceDetails } from './TebexBasketSnapshotPriceDetails';
import type { TebexBasketRowSnapshot } from './TebexBasketRowSnapshot';

export interface TebexBasketSnapshot {
	/** @nullable */
	ident?: string | null;
	/** @nullable */
	checkoutUrl?: string | null;
	/** @nullable */
	paymentUrl?: string | null;
	/** @nullable */
	completeUrl?: string | null;
	/** @nullable */
	cancelUrl?: string | null;
	/** @nullable */
	creatorCode?: string | null;
	/** @nullable */
	country?: string | null;
	/** @nullable */
	fingerprint?: string | null;
	paymentStarted: boolean;
	/** @nullable */
	expiresAt?: string | null;
	/** @nullable */
	price?: number | null;
	/** @nullable */
	priceDetails?: TebexBasketSnapshotPriceDetails;
	rows: TebexBasketRowSnapshot[];
}
