/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */

export type TextModerationTargetType = (typeof TextModerationTargetType)[keyof typeof TextModerationTargetType];

export const TextModerationTargetType = {
	feedbackPost: 'feedbackPost',
	feedbackRevision: 'feedbackRevision',
	publicComment: 'publicComment',
	bugReport: 'bugReport',
	bugReportComment: 'bugReportComment',
	guide: 'guide',
	guideRevision: 'guideRevision',
} as const;
