/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ListOfString } from './ListOfString';
import type { StringArray } from './StringArray';

/**
 * Features of the product
 */
export interface UnlockedProductFeaturesDto {
	/**
	 * ID of unlocked badge.
	 * @nullable
	 */
	badgeId?: number | null;
	weightStyles?: ListOfString | null;
	/**
	 * Ability to override other's weight styles.
	 * @nullable
	 */
	weightStyleOverride?: boolean | null;
	embedColors?: ListOfString | null;
	/**
	 * Ability to hide shop promotions.
	 * @nullable
	 */
	hideShopPromotions?: boolean | null;
	/**
	 * Show "More Info" on weight command by default.
	 * @nullable
	 */
	moreInfoDefault?: boolean | null;
	/**
	 * Ability to have custom name emoji for the user.
	 * @nullable
	 */
	customEmoji?: boolean | null;
	/**
	 * Maximum number of events that can be created in a month. (For guilds)
	 * @nullable
	 */
	maxMonthlyEvents?: number | null;
	/**
	 * Maximum number of jacob leaderboard that can be active at once. (For guilds)
	 * @nullable
	 */
	maxJacobLeaderboards?: number | null;
	flags?: StringArray | null;
}
