/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { UnparsedApiDataDtoConsumed } from './UnparsedApiDataDtoConsumed';
import type { UnparsedApiDataDtoExportedCrops } from './UnparsedApiDataDtoExportedCrops';
import type { UnparsedApiDataDtoLevelCaps } from './UnparsedApiDataDtoLevelCaps';
import type { UnparsedApiDataDtoPerks } from './UnparsedApiDataDtoPerks';
import type { TempStatBuffResponse } from './TempStatBuffResponse';
import type { UnparsedApiDataDtoAccessoryBagSettings } from './UnparsedApiDataDtoAccessoryBagSettings';
import type { UnparsedApiDataDtoBestiary } from './UnparsedApiDataDtoBestiary';
import type { UnparsedApiDataDtoDungeons } from './UnparsedApiDataDtoDungeons';

export interface UnparsedApiDataDto {
	copper: number;
	consumed: UnparsedApiDataDtoConsumed;
	/** @nullable */
	exportedCrops?: UnparsedApiDataDtoExportedCrops;
	dnaMilestone: number;
	levelCaps: UnparsedApiDataDtoLevelCaps;
	/** @nullable */
	perks?: UnparsedApiDataDtoPerks;
	/** @nullable */
	tempStatBuffs?: TempStatBuffResponse[] | null;
	/** @nullable */
	accessoryBagSettings?: UnparsedApiDataDtoAccessoryBagSettings;
	/** @nullable */
	bestiary?: UnparsedApiDataDtoBestiary;
	/** @nullable */
	dungeons?: UnparsedApiDataDtoDungeons;
}
