/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { DiscordRole } from './DiscordRole';
import type { ExcludedTimespan } from './ExcludedTimespan';
import type { GuildJacobLeaderboard } from './GuildJacobLeaderboard';

export interface UpdateJacobFeatureRequestUpdateJacobFeature {
	/** Blocked roles from participating in the guild's Jacob Leaderboards */
	blockedRoles: DiscordRole[];
	/** Blocked users from participating in the guild's Jacob Leaderboards */
	blockedUsers: bigint[];
	/** Required roles to participate in the guild's Jacob Leaderboards */
	requiredRoles: DiscordRole[];
	/** Excluded participations from the guild's Jacob Leaderboards */
	excludedParticipations: string[];
	/** Excluded timespans from the guild's Jacob Leaderboards */
	excludedTimespans: ExcludedTimespan[];
	/** Leaderboards for the guild's Jacob Leaderboards */
	leaderboards: GuildJacobLeaderboard[];
}
