/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { ConfiguredProductFeaturesDto } from './ConfiguredProductFeaturesDto';
import type { DictionaryOfStringAndLeaderboardAppearanceOverride } from './DictionaryOfStringAndLeaderboardAppearanceOverride';

export interface UpdateUserSettingsDto {
	/**
	 * Custom name prefix
	 * @nullable
	 */
	prefix?: string | null;
	/**
	 * Custom name suffix
	 * @nullable
	 */
	suffix?: string | null;
	features?: ConfiguredProductFeaturesDto | null;
	/**
	 * Selected weight style for the user
	 * @nullable
	 */
	weightStyleId?: number | null;
	/**
	 * Selected leaderboard style for the user
	 * @nullable
	 */
	leaderboardStyleId?: number | null;
	/**
	 * Selected name style for the user
	 * @nullable
	 */
	nameStyleId?: number | null;
	/** @nullable */
	pageStyleId?: number | null;
	/** @nullable */
	leaderboardFrameId?: number | null;
	/** @nullable */
	nameCardFrameId?: number | null;
	leaderboardOverrides?: DictionaryOfStringAndLeaderboardAppearanceOverride | null;
	/**
	 * If the user should be hidden from browser search indexing.
	 * @nullable
	 */
	hideFromSearchIndex?: boolean | null;
}
