/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GuideRichData } from './GuideRichData';
import type { ListOfString } from './ListOfString';

export interface UpdateGuideRequest {
	title: string;
	/** @nullable */
	iconSkyblockId?: string | null;
	description: string;
	markdownContent: string;
	tags?: ListOfString | null;
	richBlocks?: GuideRichData | null;
	/** Opaque save token for the draft version the editor loaded. */
	concurrencyVersion: number;
}
