/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { CropSettingsOfString } from './CropSettingsOfString';

export interface UpdateContestPingsRequestUpdateContestPings {
	/** Indicates whether the contest pings feature is enabled for the guild. */
	enabled: boolean;
	/**
	 * Channel ID to send contest pings to.
	 * @nullable
	 */
	channelId?: string | null;
	/**
	 * Role ID to ping when a contest starts.
	 * @nullable
	 */
	alwaysPingRole?: string | null;
	cropPingRoles?: CropSettingsOfString | null;
	/** Not in use yet. Delay in seconds before sending the ping. */
	delaySeconds: number;
	/**
	 * Reason for disabling the feature.
	 * @minLength 0
	 * @maxLength 128
	 * @nullable
	 */
	disabledReason?: string | null;
}
