/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GiftItemStateDto } from './GiftItemStateDto';
import type { TebexPackageSnapshot } from './TebexPackageSnapshot';
import type { TebexVariableData } from './TebexVariableData';

export interface UserOrderItemDto {
	orderItemId: string;
	productId: string;
	/** @nullable */
	productName?: string | null;
	quantity: number;
	unitPrice: number;
	totalPrice: number;
	/** @nullable */
	tebexPackageId?: string | null;
	tebexPackage?: TebexPackageSnapshot | null;
	tebexVariables?: TebexVariableData | null;
	gift?: GiftItemStateDto | null;
}
