/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { UserOrderItemDtoTebexPackage } from './UserOrderItemDtoTebexPackage';
import type { UserOrderItemDtoTebexVariables } from './UserOrderItemDtoTebexVariables';
import type { UserOrderItemDtoGift } from './UserOrderItemDtoGift';

export interface UserOrderItemDto {
	orderItemId: string;
	productId: string;
	/** @nullable */
	productName?: string | null;
	quantity: number;
	unitPrice: number;
	totalPrice: number;
	/** @nullable */
	tebexPackageId?: string | null;
	/** @nullable */
	tebexPackage?: UserOrderItemDtoTebexPackage;
	/** @nullable */
	tebexVariables?: UserOrderItemDtoTebexVariables;
	/** @nullable */
	gift?: UserOrderItemDtoGift;
}
