/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { GlassTextStyle } from './GlassTextStyle';
import type { WeightStyleElementOutline } from './WeightStyleElementOutline';
import type { WeightStylePosition } from './WeightStylePosition';
import type { WeightStyleTextBackground } from './WeightStyleTextBackground';

export interface WeightStyleElement {
	/** @nullable */
	font?: string | null;
	/** @nullable */
	fill?: string | null;
	/** @nullable */
	fontSize?: number | null;
	position: WeightStylePosition;
	/** @nullable */
	maxWidth?: number | null;
	/** @nullable */
	maxHeight?: number | null;
	outline?: WeightStyleElementOutline | null;
	background?: WeightStyleTextBackground | null;
	glass?: GlassTextStyle | null;
}
