/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { WeightStylePosition } from './WeightStylePosition';
import type { WeightStyleElementOutlineProperty } from './WeightStyleElementOutlineProperty';
import type { WeightStyleElementBackground } from './WeightStyleElementBackground';

export interface WeightStyleElement {
	/** @nullable */
	font?: string | null;
	/** @nullable */
	fill?: string | null;
	/** @nullable */
	fontSize?: number | null;
	position: WeightStylePosition;
	/** @nullable */
	maxWidth?: number | null;
	/** @nullable */
	maxHeight?: number | null;
	/** @nullable */
	outline?: WeightStyleElementOutlineProperty;
	/** @nullable */
	background?: WeightStyleElementBackground;
}
