/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { WeightStyleDecalDto } from './WeightStyleDecalDto';
import type { WeightStyleElementsDto } from './WeightStyleElementsDto';

export interface WeightStyleDataDto {
	decal?: WeightStyleDecalDto | null;
	elements: WeightStyleElementsDto;
}
