/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
 * <br><br>
 * Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { AuthorDto } from './AuthorDto';
import type { CosmeticCapabilitiesDto } from './CosmeticCapabilitiesDto';
import type { CosmeticType } from './CosmeticType';
import type { DictionaryOfStringAndImageAttachmentDto } from './DictionaryOfStringAndImageAttachmentDto';
import type { FrameStyleDataDto } from './FrameStyleDataDto';
import type { ImageAttachmentDto } from './ImageAttachmentDto';
import type { LeaderboardStyleDataDto } from './LeaderboardStyleDataDto';
import type { ListOfImageAttachmentDto } from './ListOfImageAttachmentDto';
import type { ListOfParentProductDto } from './ListOfParentProductDto';
import type { NameCardStyleDataDto } from './NameCardStyleDataDto';
import type { PageStyleDataDto } from './PageStyleDataDto';
import type { WeightStyleDataDto } from './WeightStyleDataDto';

export interface WeightStyleWithDataDto {
	data?: WeightStyleDataDto | null;
	leaderboard?: LeaderboardStyleDataDto | null;
	nameCard?: NameCardStyleDataDto | null;
	page?: PageStyleDataDto | null;
	frame?: FrameStyleDataDto | null;
	imageRefs: DictionaryOfStringAndImageAttachmentDto;
	id: number;
	type: CosmeticType;
	capabilities: CosmeticCapabilitiesDto;
	published: boolean;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	styleFormatter?: string | null;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	name?: string | null;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	collection?: string | null;
	/**
	 * @maxLength 1024
	 * @nullable
	 */
	description?: string | null;
	image?: ImageAttachmentDto | null;
	author?: AuthorDto | null;
	images: ListOfImageAttachmentDto;
	products: ListOfParentProductDto;
}
