/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { WeightStyleBackgroundSize } from './WeightStyleBackgroundSize';
import type { WeightStyleBackgroundRect } from './WeightStyleBackgroundRect';

export interface WeightStyleBackground {
	/** @nullable */
	size?: WeightStyleBackgroundSize;
	/** @nullable */
	fill?: string | null;
	/** @nullable */
	rects?: WeightStyleBackgroundRect[] | null;
	/** @nullable */
	imageUrl?: string | null;
	/** @nullable */
	radius?: number | null;
	/** @nullable */
	opacity?: number | null;
}
