/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://eliteskyblock.com/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://eliteskyblock.com/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: admin-v1
 */
import type { WeightStyleListDtoAuthor } from './WeightStyleListDtoAuthor';
import type { WeightStyleListDtoData } from './WeightStyleListDtoData';
import type { WeightStyleListDtoLeaderboard } from './WeightStyleListDtoLeaderboard';
import type { WeightStyleListDtoImageRefs } from './WeightStyleListDtoImageRefs';
import type { CosmeticCapabilitiesDto, FrameStyleDataDto, PageStyleDataDto } from './CosmeticPayloads';
import type { NameCardStyleDataDto } from './NameCardStyleDataDto';

export interface WeightStyleListDto {
	id: number;
	type?: 0 | 1;
	capabilities?: CosmeticCapabilitiesDto;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	styleFormatter?: string | null;
	/**
	 * @maxLength 64
	 * @nullable
	 */
	name?: string | null;
	/**
	 * @maxLength 1024
	 * @nullable
	 */
	description?: string | null;
	/** @nullable */
	author?: WeightStyleListDtoAuthor;
	/** @nullable */
	data?: WeightStyleListDtoData;
	/** @nullable */
	leaderboard?: WeightStyleListDtoLeaderboard;
	nameCard?: NameCardStyleDataDto | null;
	page?: PageStyleDataDto | null;
	frame?: FrameStyleDataDto | null;
	imageRefs: WeightStyleListDtoImageRefs;
}
