/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Elite API
 * A backend API for https://elitebot.dev/ that provides Hypixel Skyblock data.
<br><br>
Use of this API requires following the [Elite API TOS](https://elitebot.dev/apiterms). This API is not affiliated with Hypixel or Mojang.
 * OpenAPI spec version: v1
 */
import type { PlayerRecapInfo } from './PlayerRecapInfo';
import type { ProfileRecapInfo } from './ProfileRecapInfo';
import type { AllProfilesSummaryRecap } from './AllProfilesSummaryRecap';
import type { ContestRecap } from './ContestRecap';
import type { EventRecap } from './EventRecap';
import type { ShopRecap } from './ShopRecap';
import type { CollectionRecap } from './CollectionRecap';
import type { PestRecap } from './PestRecap';
import type { SkillRecap } from './SkillRecap';
import type { StreakRecap } from './StreakRecap';
import type { LeaderboardRecap } from './LeaderboardRecap';

export interface YearlyRecapData {
	player: PlayerRecapInfo;
	profiles: ProfileRecapInfo[];
	allProfilesSummary: AllProfilesSummaryRecap;
	contests: ContestRecap;
	events: EventRecap[];
	shop: ShopRecap;
	collections: CollectionRecap;
	pests: PestRecap;
	skills: SkillRecap;
	streak: StreakRecap;
	leaderboards: LeaderboardRecap;
	year: string;
	currentProfile: string;
}
