name: Setup
description: Setup pnpm cache
input:
output:
runs:
    using: 'composite'
    steps:
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 23

        - uses: pnpm/action-setup@v2
          name: Install pnpm
          with:
              version: 10
              run_install: false

        - name: Get pnpm store directory
          shell: bash
          run: |
              echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

        - uses: actions/cache@v4
          name: Setup pnpm cache
          with:
              path: ${{ env.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-store-

        - name: Install dependencies
          shell: bash
          run: pnpm install

        - name: Make dummy env for types
          shell: bash
          run: |
              echo "ls -a ."
              ls -a .
              mv .env.example .env
