export enum LeaderboardType {
	Misc = 0,
	Collection = 1,
	Skill = 2,
	Pest = 3,
	Milestone = 4,
}

export interface LeaderboardConfig {
	limit: number;
	type: LeaderboardType;
	name: string;
	icon?: string;
	title: string;
	profile?: boolean;
	overflow?: boolean;
	subpage?: string;
}

export const LEADERBOARDS: Record<string, LeaderboardConfig> = {
	farmingweight: {
		limit: 10_000,
		title: 'Farming Weight',
		name: 'Farming Weight',
		type: LeaderboardType.Misc,
	},
	garden: {
		name: 'Garden',
		title: 'Garden XP',
		limit: 5_000,
		type: LeaderboardType.Misc,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	skyblockxp: {
		limit: 5_000,
		title: 'Skyblock Level',
		name: 'Skyblock Level',
		type: LeaderboardType.Misc,
	},
	chocolate: {
		limit: 5_000,
		title: 'All-Time Chocolate',
		name: 'Chocolate',
		type: LeaderboardType.Misc,
	},
	participations: {
		limit: 1_000,
		title: 'Jacob Contest Participations',
		name: 'Jacob Contests',
		type: LeaderboardType.Misc,
	},
	'visitors-accepted': {
		limit: 5_000,
		title: 'Visitors Accepted',
		name: 'Visitors Accepted',
		type: LeaderboardType.Misc,
		profile: true,
		subpage: '/garden',
	},
	firstplace: {
		limit: 1_000,
		title: 'Jacob Contest First Places',
		name: 'First Place Contests',
		type: LeaderboardType.Misc,
	},
	diamondmedals: {
		limit: 1_000,
		title: 'Diamond Medals Earned',
		name: 'Diamond Medals',
		icon: '/images/medals/diamond.webp',
		type: LeaderboardType.Misc,
	},
	platinummedals: {
		limit: 1_000,
		title: 'Platinum Medals Earned',
		name: 'Platinum Medals',
		icon: '/images/medals/platinum.webp',
		type: LeaderboardType.Misc,
	},
	goldmedals: {
		limit: 1_000,
		title: 'Gold Medals Earned',
		name: 'Gold Medals',
		icon: '/images/medals/gold.webp',
		type: LeaderboardType.Misc,
	},
	silvermedals: {
		limit: 1_000,
		title: 'Silver Medals Earned',
		name: 'Silver Medals',
		icon: '/images/medals/silver.webp',
		type: LeaderboardType.Misc,
	},
	bronzemedals: {
		limit: 1_000,
		title: 'Bronze Medals Earned',
		name: 'Bronze Medals',
		icon: '/images/medals/bronze.webp',
		type: LeaderboardType.Misc,
	},
	cactus: {
		limit: 5_000,
		title: 'Cactus Collection',
		name: 'Cactus',
		icon: '/images/crops/cactus.png',
		type: LeaderboardType.Collection,
	},
	carrot: {
		limit: 5_000,
		title: 'Carrot Collection',
		name: 'Carrot',
		icon: '/images/crops/carrot.png',
		type: LeaderboardType.Collection,
	},
	potato: {
		limit: 5_000,
		title: 'Potato Collection',
		name: 'Potato',
		icon: '/images/crops/potato.png',
		type: LeaderboardType.Collection,
	},
	pumpkin: {
		limit: 5_000,
		title: 'Pumpkin Collection',
		name: 'Pumpkin',
		icon: '/images/crops/pumpkin.png',
		type: LeaderboardType.Collection,
	},
	wheat: {
		limit: 5_000,
		title: 'Wheat Collection',
		name: 'Wheat',
		icon: '/images/crops/wheat.png',
		type: LeaderboardType.Collection,
	},
	melon: {
		limit: 5_000,
		title: 'Melon Collection',
		name: 'Melon',
		icon: '/images/crops/melon.png',
		type: LeaderboardType.Collection,
	},
	mushroom: {
		limit: 5_000,
		title: 'Mushroom Collection',
		name: 'Mushroom',
		icon: '/images/crops/mushroom.png',
		type: LeaderboardType.Collection,
	},
	cocoa: {
		limit: 5_000,
		title: 'Cocoa Bean Collection',
		name: 'Cocoa Bean',
		icon: '/images/crops/cocoa.png',
		type: LeaderboardType.Collection,
	},
	sugarcane: {
		limit: 5_000,
		title: 'Sugar Cane Collection',
		name: 'Sugar Cane',
		icon: '/images/crops/sugarcane.png',
		type: LeaderboardType.Collection,
	},
	netherwart: {
		limit: 5_000,
		title: 'Nether Wart Collection',
		name: 'Nether Wart',
		icon: '/images/crops/netherwart.png',
		type: LeaderboardType.Collection,
	},
	combat: {
		limit: 5_000,
		title: 'Combat XP',
		name: 'Combat',
		type: LeaderboardType.Skill,
	},
	mining: {
		limit: 5_000,
		title: 'Mining XP',
		name: 'Mining',
		type: LeaderboardType.Skill,
	},
	foraging: {
		limit: 5_000,
		title: 'Foraging XP',
		name: 'Foraging',
		type: LeaderboardType.Skill,
	},
	fishing: {
		limit: 5_000,
		title: 'Fishing XP',
		name: 'Fishing',
		type: LeaderboardType.Skill,
	},
	enchanting: {
		limit: 5_000,
		title: 'Enchanting XP',
		name: 'Enchanting',
		type: LeaderboardType.Skill,
	},
	alchemy: {
		limit: 5_000,
		title: 'Alchemy XP',
		name: 'Alchemy',
		type: LeaderboardType.Skill,
	},
	taming: {
		limit: 5_000,
		title: 'Taming XP',
		name: 'Taming',
		type: LeaderboardType.Skill,
	},
	carpentry: {
		limit: 5_000,
		title: 'Carpentry XP',
		name: 'Carpentry',
		type: LeaderboardType.Skill,
	},
	runecrafting: {
		limit: 5_000,
		title: 'Runecrafting XP',
		name: 'Runecrafting',
		type: LeaderboardType.Skill,
	},
	social: {
		limit: 5_000,
		title: 'Social XP',
		name: 'Social',
		type: LeaderboardType.Skill,
	},
	farming: {
		limit: 5_000,
		title: 'Farming XP',
		name: 'Farming',
		type: LeaderboardType.Skill,
	},
	mite: {
		name: 'Mite',
		title: 'Mite Kills',
		limit: 5_000,
		icon: '/images/pests/mite.png',
		type: LeaderboardType.Pest,
	},
	cricket: {
		name: 'Cricket',
		title: 'Cricket Kills',
		limit: 5_000,
		icon: '/images/pests/cricket.png',
		type: LeaderboardType.Pest,
	},
	moth: {
		name: 'Moth',
		title: 'Moth Kills',
		limit: 5_000,
		icon: '/images/pests/moth.png',
		type: LeaderboardType.Pest,
	},
	earthworm: {
		name: 'Earthworm',
		title: 'Earthworm Kills',
		limit: 5_000,
		icon: '/images/pests/earthworm.png',
		type: LeaderboardType.Pest,
	},
	slug: {
		name: 'Slug',
		title: 'Slug Kills',
		limit: 5_000,
		icon: '/images/pests/slug.png',
		type: LeaderboardType.Pest,
	},
	beetle: {
		name: 'Beetle',
		title: 'Beetle Kills',
		limit: 5_000,
		icon: '/images/pests/beetle.png',
		type: LeaderboardType.Pest,
	},
	locust: {
		name: 'Locust',
		title: 'Locust Kills',
		limit: 5_000,
		icon: '/images/pests/locust.png',
		type: LeaderboardType.Pest,
	},
	rat: {
		name: 'Rat',
		title: 'Rat Kills',
		limit: 5_000,
		icon: '/images/pests/rat.png',
		type: LeaderboardType.Pest,
	},
	mosquito: {
		name: 'Mosquito',
		title: 'Mosquito Kills',
		limit: 5_000,
		icon: '/images/pests/mosquito.png',
		type: LeaderboardType.Pest,
	},
	fly: {
		name: 'Fly',
		title: 'Fly Kills',
		limit: 5_000,
		icon: '/images/pests/fly.png',
		type: LeaderboardType.Pest,
	},
	mouse: {
		name: 'Field Mouse',
		title: 'Field Mouse Kills',
		limit: 5_000,
		type: LeaderboardType.Pest,
	},
	'cactus-milestone': {
		limit: 5_000,
		title: 'Cactus Milestone Collection',
		name: 'Cactus Milestone',
		icon: '/images/crops/cactus.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'carrot-milestone': {
		limit: 5_000,
		title: 'Carrot Milestone Collection',
		name: 'Carrot Milestone',
		icon: '/images/crops/carrot.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'potato-milestone': {
		limit: 5_000,
		title: 'Potato Milestone Collection',
		name: 'Potato Milestone',
		icon: '/images/crops/potato.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'pumpkin-milestone': {
		limit: 5_000,
		title: 'Pumpkin Milestone Collection',
		name: 'Pumpkin Milestone',
		icon: '/images/crops/pumpkin.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'wheat-milestone': {
		limit: 5_000,
		title: 'Wheat Milestone Collection',
		name: 'Wheat Milestone',
		icon: '/images/crops/wheat.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'melon-milestone': {
		limit: 5_000,
		title: 'Melon Milestone Collection',
		name: 'Melon Milestone',
		icon: '/images/crops/melon.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'mushroom-milestone': {
		limit: 5_000,
		title: 'Mushroom Milestone Collection',
		name: 'Mushroom	Milestone',
		icon: '/images/crops/mushroom.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'cocoa-milestone': {
		limit: 5_000,
		title: 'Cocoa Bean Milestone Collection',
		name: 'Cocoa Bean Milestone',
		icon: '/images/crops/cocoa.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'sugarcane-milestone': {
		limit: 5_000,
		title: 'Sugar Cane Milestone Collection',
		name: 'Sugar Cane Milestone',
		icon: '/images/crops/sugarcane.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
	'netherwart-milestone': {
		limit: 5_000,
		title: 'Nether Wart Milestone Collection',
		name: 'Nether Wart Milestone',
		icon: '/images/crops/netherwart.png',
		type: LeaderboardType.Milestone,
		profile: true,
		overflow: true,
		subpage: '/garden',
	},
};

export const REDIRECT_ROUTES: Record<string, string> = {
	'/weight/farming': '/farmingweight',
	'/contests/count': '/participations',
	'/crops/cactus': '/cactus',
	'/crops/carrot': '/carrot',
	'/crops/potato': '/potato',
	'/crops/pumpkin': '/pumpkin',
	'/crops/wheat': '/wheat',
	'/crops/melon': '/melon',
	'/crops/mushroom': '/mushroom',
	'/crops/cocoa': '/cocoa',
	'/crops/sugarcane': '/sugarcane',
	'/crops/netherwart': '/netherwart',
	'/skills/combat': '/combat',
	'/skills/mining': '/mining',
	'/skills/foraging': '/foraging',
	'/skills/fishing': '/fishing',
	'/skills/enchanting': '/enchanting',
	'/skills/alchemy': '/alchemy',
	'/skills/taming': '/taming',
	'/skills/carpentry': '/carpentry',
	'/skills/runecrafting': '/runecrafting',
	'/skills/social': '/social',
	'/skills/farming': '/farming',
};
