export const ITEM_IDS = {
	EnchantedWheat: 'ENCHANTED_WHEAT',
	EnchantedGoldenCarrot: 'ENCHANTED_GOLDEN_CARROT',
	EnchantedHayBale: 'ENCHANTED_HAY_BALE',
	Cropie: 'CROPIE',
	Squash: 'SQUASH',
	Fermento: 'FERMENTO',
	CondensedFermento: 'CONDENSED_FERMENTO',
	EnchantedBakedPotato: 'ENCHANTED_BAKED_POTATO',
	EnchantedPumpkin: 'ENCHANTED_PUMPKIN',
	PolishedPumpkin: 'POLISHED_PUMPKIN',
	EnchantedSugarCane: 'ENCHANTED_SUGAR_CANE',
	EnchantedMelonBlock: 'ENCHANTED_MELON_BLOCK',
	EnchantedCactus: 'ENCHANTED_CACTUS',
	EnchantedCookie: 'ENCHANTED_COOKIE',
	EnchantedBrownMushroom: 'ENCHANTED_BROWN_MUSHROOM',
	EnchantedRedMushroom: 'ENCHANTED_RED_MUSHROOM',
	EnchantedRedMushroomBlock: 'ENCHANTED_HUGE_MUSHROOM_2',
	EnchantedBrownMushroomBlock: 'ENCHANTED_HUGE_MUSHROOM_1',
	EnchantedNetherWart: 'ENCHANTED_NETHER_STALK',
	MutantNetherWart: 'MUTANT_NETHER_STALK',
} as const;
