/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * StreamAPI
 * OpenAPI spec version: v1
 */
import type {
	GetLiveStreamsParams,
	StreamAPIModelsLiveStreamsResponse,
	StreamAPIModelsStreamerDirectoryResponse,
	StreamAPIModelsStreamerProfileResponse,
} from '../schemas';

import { customFetch } from '../custom-fetch';
import { env } from '$env/dynamic/private';
const { STREAM_API_URL } = env;

/**
 * Returns saved live streamers first, then keyword-matched Twitch streams.
 * @summary Lists currently live streams.
 */
export type getLiveStreamsResponse200 = {
	data: StreamAPIModelsLiveStreamsResponse;
	status: 200;
};

export type getLiveStreamsResponseSuccess = getLiveStreamsResponse200 & {
	headers: Headers;
};
export type getLiveStreamsResponse = getLiveStreamsResponseSuccess;

export const getGetLiveStreamsUrl = (params: GetLiveStreamsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${STREAM_API_URL}/streams/live?${stringifiedParams}`
		: `${STREAM_API_URL}/streams/live`;
};

export const getLiveStreams = async (params: GetLiveStreamsParams, options?: RequestInit) => {
	return customFetch<getLiveStreamsResponse>(getGetLiveStreamsUrl(params), {
		...options,
		method: 'GET',
	});
};

/**
 * Looks up persisted streamer metadata by Twitch login.
 * @summary Gets one saved streamer profile.
 */
export type getStreamerResponse200 = {
	data: StreamAPIModelsStreamerProfileResponse;
	status: 200;
};

export type getStreamerResponseSuccess = getStreamerResponse200 & {
	headers: Headers;
};
export type getStreamerResponse = getStreamerResponseSuccess;

export const getGetStreamerUrl = (twitchLogin: string) => {
	return `${STREAM_API_URL}/streamers/${twitchLogin}`;
};

export const getStreamer = async (twitchLogin: string, options?: RequestInit) => {
	return customFetch<getStreamerResponse>(getGetStreamerUrl(twitchLogin), {
		...options,
		method: 'GET',
	});
};

/**
 * Returns promoted streamer profiles with live stream metadata when they are currently live.
 * @summary Lists registered streamer profiles.
 */
export type listStreamersResponse200 = {
	data: StreamAPIModelsStreamerDirectoryResponse;
	status: 200;
};

export type listStreamersResponseSuccess = listStreamersResponse200 & {
	headers: Headers;
};
export type listStreamersResponse = listStreamersResponseSuccess;

export const getListStreamersUrl = () => {
	return `${STREAM_API_URL}/streamers`;
};

export const listStreamers = async (options?: RequestInit) => {
	return customFetch<listStreamersResponse>(getListStreamersUrl(), {
		...options,
		method: 'GET',
	});
};
