/**
 * Generated by orval 🍺
 * Do not edit manually.
 * StreamAPI
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

/**
 * Returns saved live streamers first, then keyword-matched Twitch streams.
 * @summary Lists currently live streams.
 */
export const zodGetLiveStreamsQueryParams = zod.object({
	provider: zod.string().nullish(),
	limit: zod.int(),
});

/**
 * Looks up persisted streamer metadata by Twitch login.
 * @summary Gets one saved streamer profile.
 */
export const zodGetStreamerParams = zod.object({
	twitchLogin: zod.string(),
});
