import { GemRarity } from '../fortune/item.js';
import { Rarity } from './reforges.js';
import { Stat } from './stats.js';

export const GEMSTONES: Record<string, GemstoneInfo> = {
	RUBY: {
		stat: Stat.Health,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 3,
				[Rarity.Epic]: 4,
				[Rarity.Legendary]: 5,
				[Rarity.Mythic]: 7,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 4,
				[Rarity.Rare]: 5,
				[Rarity.Epic]: 6,
				[Rarity.Legendary]: 8,
				[Rarity.Mythic]: 10,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 4,
				[Rarity.Uncommon]: 5,
				[Rarity.Rare]: 6,
				[Rarity.Epic]: 8,
				[Rarity.Legendary]: 10,
				[Rarity.Mythic]: 14,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 5,
				[Rarity.Uncommon]: 7,
				[Rarity.Rare]: 10,
				[Rarity.Epic]: 14,
				[Rarity.Legendary]: 18,
				[Rarity.Mythic]: 22,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 6,
				[Rarity.Uncommon]: 9,
				[Rarity.Rare]: 13,
				[Rarity.Epic]: 18,
				[Rarity.Legendary]: 24,
				[Rarity.Mythic]: 30,
			},
		},
	},
	AMBER: {
		stat: Stat.MiningSpeed,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 4,
				[Rarity.Uncommon]: 8,
				[Rarity.Rare]: 12,
				[Rarity.Epic]: 16,
				[Rarity.Legendary]: 20,
				[Rarity.Mythic]: 24,
				[Rarity.Divine]: 28,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 6,
				[Rarity.Uncommon]: 10,
				[Rarity.Rare]: 14,
				[Rarity.Epic]: 18,
				[Rarity.Legendary]: 24,
				[Rarity.Mythic]: 30,
				[Rarity.Divine]: 36,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 10,
				[Rarity.Uncommon]: 14,
				[Rarity.Rare]: 20,
				[Rarity.Epic]: 28,
				[Rarity.Legendary]: 36,
				[Rarity.Mythic]: 45,
				[Rarity.Divine]: 54,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 14,
				[Rarity.Uncommon]: 20,
				[Rarity.Rare]: 30,
				[Rarity.Epic]: 44,
				[Rarity.Legendary]: 58,
				[Rarity.Mythic]: 75,
				[Rarity.Divine]: 92,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 20,
				[Rarity.Uncommon]: 28,
				[Rarity.Rare]: 40,
				[Rarity.Epic]: 60,
				[Rarity.Legendary]: 80,
				[Rarity.Mythic]: 100,
				[Rarity.Divine]: 120,
			},
		},
	},
	TOPAZ: {
		stat: Stat.Pristine,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 0.4,
				[Rarity.Uncommon]: 0.4,
				[Rarity.Rare]: 0.4,
				[Rarity.Epic]: 0.4,
				[Rarity.Legendary]: 0.4,
				[Rarity.Mythic]: 0.4,
				[Rarity.Divine]: 0.5,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 0.8,
				[Rarity.Uncommon]: 0.8,
				[Rarity.Rare]: 0.8,
				[Rarity.Epic]: 0.8,
				[Rarity.Legendary]: 0.8,
				[Rarity.Mythic]: 0.8,
				[Rarity.Divine]: 0.9,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 1.2,
				[Rarity.Uncommon]: 1.2,
				[Rarity.Rare]: 1.2,
				[Rarity.Epic]: 1.2,
				[Rarity.Legendary]: 1.2,
				[Rarity.Mythic]: 1.2,
				[Rarity.Divine]: 1.3,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 1.6,
				[Rarity.Uncommon]: 1.6,
				[Rarity.Rare]: 1.6,
				[Rarity.Epic]: 1.6,
				[Rarity.Legendary]: 1.6,
				[Rarity.Mythic]: 1.6,
				[Rarity.Divine]: 1.8,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 2,
				[Rarity.Epic]: 2,
				[Rarity.Legendary]: 2,
				[Rarity.Mythic]: 2,
				[Rarity.Divine]: 2.2,
			},
		},
	},
	JADE: {
		stat: Stat.MiningFortune,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 4,
				[Rarity.Rare]: 6,
				[Rarity.Epic]: 8,
				[Rarity.Legendary]: 10,
				[Rarity.Mythic]: 12,
				[Rarity.Divine]: 14,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 5,
				[Rarity.Rare]: 7,
				[Rarity.Epic]: 10,
				[Rarity.Legendary]: 14,
				[Rarity.Mythic]: 18,
				[Rarity.Divine]: 22,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 5,
				[Rarity.Uncommon]: 7,
				[Rarity.Rare]: 10,
				[Rarity.Epic]: 15,
				[Rarity.Legendary]: 20,
				[Rarity.Mythic]: 25,
				[Rarity.Divine]: 30,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 7,
				[Rarity.Uncommon]: 10,
				[Rarity.Rare]: 15,
				[Rarity.Epic]: 20,
				[Rarity.Legendary]: 27,
				[Rarity.Mythic]: 35,
				[Rarity.Divine]: 44,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 10,
				[Rarity.Uncommon]: 14,
				[Rarity.Rare]: 20,
				[Rarity.Epic]: 30,
				[Rarity.Legendary]: 40,
				[Rarity.Mythic]: 50,
				[Rarity.Divine]: 60,
			},
		},
	},
	SAPPHIRE: {
		stat: Stat.Intelligence,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 3,
				[Rarity.Rare]: 4,
				[Rarity.Epic]: 5,
				[Rarity.Legendary]: 6,
				[Rarity.Mythic]: 7,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 5,
				[Rarity.Uncommon]: 5,
				[Rarity.Rare]: 6,
				[Rarity.Epic]: 7,
				[Rarity.Legendary]: 8,
				[Rarity.Mythic]: 10,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 7,
				[Rarity.Uncommon]: 8,
				[Rarity.Rare]: 9,
				[Rarity.Epic]: 10,
				[Rarity.Legendary]: 11,
				[Rarity.Mythic]: 12,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 10,
				[Rarity.Uncommon]: 11,
				[Rarity.Rare]: 12,
				[Rarity.Epic]: 14,
				[Rarity.Legendary]: 17,
				[Rarity.Mythic]: 20,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 12,
				[Rarity.Uncommon]: 14,
				[Rarity.Rare]: 17,
				[Rarity.Epic]: 20,
				[Rarity.Legendary]: 24,
				[Rarity.Mythic]: 30,
			},
		},
	},
	AMETHYST: {
		stat: Stat.Defense,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 3,
				[Rarity.Epic]: 4,
				[Rarity.Legendary]: 5,
				[Rarity.Mythic]: 7,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 4,
				[Rarity.Rare]: 5,
				[Rarity.Epic]: 6,
				[Rarity.Legendary]: 8,
				[Rarity.Mythic]: 10,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 4,
				[Rarity.Uncommon]: 5,
				[Rarity.Rare]: 6,
				[Rarity.Epic]: 8,
				[Rarity.Legendary]: 10,
				[Rarity.Mythic]: 14,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 5,
				[Rarity.Uncommon]: 7,
				[Rarity.Rare]: 10,
				[Rarity.Epic]: 14,
				[Rarity.Legendary]: 18,
				[Rarity.Mythic]: 22,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 6,
				[Rarity.Uncommon]: 9,
				[Rarity.Rare]: 13,
				[Rarity.Epic]: 18,
				[Rarity.Legendary]: 24,
				[Rarity.Mythic]: 30,
			},
		},
	},
	JASPER: {
		stat: Stat.Strength,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 1,
				[Rarity.Rare]: 1,
				[Rarity.Epic]: 2,
				[Rarity.Legendary]: 3,
				[Rarity.Mythic]: 4,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 3,
				[Rarity.Epic]: 4,
				[Rarity.Legendary]: 4,
				[Rarity.Mythic]: 5,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 3,
				[Rarity.Rare]: 4,
				[Rarity.Epic]: 5,
				[Rarity.Legendary]: 6,
				[Rarity.Mythic]: 7,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 5,
				[Rarity.Uncommon]: 6,
				[Rarity.Rare]: 7,
				[Rarity.Epic]: 8,
				[Rarity.Legendary]: 10,
				[Rarity.Mythic]: 12,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 6,
				[Rarity.Uncommon]: 7,
				[Rarity.Rare]: 9,
				[Rarity.Epic]: 11,
				[Rarity.Legendary]: 13,
				[Rarity.Mythic]: 16,
			},
		},
	},
	OPAL: {
		stat: Stat.TrueDefense,
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 1,
				[Rarity.Rare]: 1,
				[Rarity.Epic]: 2,
				[Rarity.Legendary]: 2,
				[Rarity.Mythic]: 3,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 2,
				[Rarity.Epic]: 3,
				[Rarity.Legendary]: 3,
				[Rarity.Mythic]: 4,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 3,
				[Rarity.Rare]: 3,
				[Rarity.Epic]: 4,
				[Rarity.Legendary]: 4,
				[Rarity.Mythic]: 5,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 4,
				[Rarity.Uncommon]: 4,
				[Rarity.Rare]: 5,
				[Rarity.Epic]: 6,
				[Rarity.Legendary]: 8,
				[Rarity.Mythic]: 9,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 5,
				[Rarity.Uncommon]: 6,
				[Rarity.Rare]: 7,
				[Rarity.Epic]: 9,
				[Rarity.Legendary]: 11,
				[Rarity.Mythic]: 13,
			},
		},
	},
	AQUAMARINE: {
		stat: Stat.FishingSpeed,
		chiselBonus: '§a{}% §7chance to gain an additional Chisel §echarge §7upon starting the §6Fossil Excavator§7.',
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 0.5,
				[Rarity.Uncommon]: 0.5,
				[Rarity.Rare]: 1,
				[Rarity.Epic]: 1,
				[Rarity.Legendary]: 1.5,
				[Rarity.Mythic]: 2,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 1,
				[Rarity.Rare]: 1.5,
				[Rarity.Epic]: 1.5,
				[Rarity.Legendary]: 2,
				[Rarity.Mythic]: 2.5,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 1.5,
				[Rarity.Uncommon]: 1.5,
				[Rarity.Rare]: 2,
				[Rarity.Epic]: 2,
				[Rarity.Legendary]: 2.5,
				[Rarity.Mythic]: 3,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 2.5,
				[Rarity.Epic]: 3,
				[Rarity.Legendary]: 3.5,
				[Rarity.Mythic]: 4,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 2.5,
				[Rarity.Uncommon]: 2.5,
				[Rarity.Rare]: 3.5,
				[Rarity.Epic]: 4,
				[Rarity.Legendary]: 4.5,
				[Rarity.Mythic]: 5,
			},
		},
	},
	CITRINE: {
		stat: Stat.ForagingFortune,
		chiselBonus: '§a{}% §7chance to §ehighlight §7a piece of treasure upon starting the §6Fossil Excavator§7.',
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 0.5,
				[Rarity.Uncommon]: 1,
				[Rarity.Rare]: 1.5,
				[Rarity.Epic]: 2,
				[Rarity.Legendary]: 2.5,
				[Rarity.Mythic]: 3,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 1.5,
				[Rarity.Rare]: 2,
				[Rarity.Epic]: 2.5,
				[Rarity.Legendary]: 3,
				[Rarity.Mythic]: 4,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 1.5,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 3,
				[Rarity.Epic]: 4,
				[Rarity.Legendary]: 5,
				[Rarity.Mythic]: 6,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 3,
				[Rarity.Rare]: 4,
				[Rarity.Epic]: 5,
				[Rarity.Legendary]: 6,
				[Rarity.Mythic]: 8,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 4,
				[Rarity.Rare]: 5,
				[Rarity.Epic]: 6,
				[Rarity.Legendary]: 8,
				[Rarity.Mythic]: 10,
			},
		},
	},
	ONYX: {
		stat: Stat.CritDamage,
		chiselBonus:
			'§a{}% §7chance to §espawn §7an additional piece of treasure upon starting the §6Fossil Excavator§7.',
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 1,
				[Rarity.Rare]: 2,
				[Rarity.Epic]: 2,
				[Rarity.Legendary]: 3,
				[Rarity.Mythic]: 4,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 3,
				[Rarity.Epic]: 3,
				[Rarity.Legendary]: 4,
				[Rarity.Mythic]: 6,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 3,
				[Rarity.Rare]: 4,
				[Rarity.Epic]: 5,
				[Rarity.Legendary]: 6,
				[Rarity.Mythic]: 8,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 4,
				[Rarity.Uncommon]: 5,
				[Rarity.Rare]: 6,
				[Rarity.Epic]: 7,
				[Rarity.Legendary]: 8,
				[Rarity.Mythic]: 10,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 5,
				[Rarity.Uncommon]: 6,
				[Rarity.Rare]: 7,
				[Rarity.Epic]: 8,
				[Rarity.Legendary]: 10,
				[Rarity.Mythic]: 12,
			},
		},
	},
	PERIDOT: {
		stat: Stat.FarmingFortune,
		chiselBonus: '§7Gain §a+{}% §dFossil Dust §7when using the §6Fossil Excavator§7.',
		stats: {
			[GemRarity.Rough]: {
				[Rarity.Common]: 0.5,
				[Rarity.Uncommon]: 1,
				[Rarity.Rare]: 1.5,
				[Rarity.Epic]: 2,
				[Rarity.Legendary]: 2.5,
				[Rarity.Mythic]: 3,
			},
			[GemRarity.Flawed]: {
				[Rarity.Common]: 1,
				[Rarity.Uncommon]: 1.5,
				[Rarity.Rare]: 2,
				[Rarity.Epic]: 2.5,
				[Rarity.Legendary]: 3,
				[Rarity.Mythic]: 4,
			},
			[GemRarity.Fine]: {
				[Rarity.Common]: 1.5,
				[Rarity.Uncommon]: 2,
				[Rarity.Rare]: 3,
				[Rarity.Epic]: 4,
				[Rarity.Legendary]: 5,
				[Rarity.Mythic]: 6,
			},
			[GemRarity.Flawless]: {
				[Rarity.Common]: 2,
				[Rarity.Uncommon]: 3,
				[Rarity.Rare]: 4,
				[Rarity.Epic]: 5,
				[Rarity.Legendary]: 6,
				[Rarity.Mythic]: 8,
			},
			[GemRarity.Perfect]: {
				[Rarity.Common]: 3,
				[Rarity.Uncommon]: 4,
				[Rarity.Rare]: 5,
				[Rarity.Epic]: 6,
				[Rarity.Legendary]: 8,
				[Rarity.Mythic]: 10,
			},
		},
	},
};

export const PERIDOT = { ...(GEMSTONES['PERIDOT']?.stats ?? {}) };

export interface GemstoneInfo {
	stat: Stat;
	chiselBonus?: string;
	stats: Partial<Record<GemRarity, Partial<Record<Rarity, number>>>>;
}
