export const ITEM_IDS = {
	EnchantedWheat: 'ENCHANTED_WHEAT',
	EnchantedGoldenCarrot: 'ENCHANTED_GOLDEN_CARROT',
	EnchantedHayBale: 'ENCHANTED_HAY_BALE',
	Cropie: 'CROPIE',
	Squash: 'SQUASH',
	Fermento: 'FERMENTO',
	CondensedFermento: 'CONDENSED_FERMENTO',
	EnchantedBakedPotato: 'ENCHANTED_BAKED_POTATO',
	EnchantedPumpkin: 'ENCHANTED_PUMPKIN',
	PolishedPumpkin: 'POLISHED_PUMPKIN',
	EnchantedSugarCane: 'ENCHANTED_SUGAR_CANE',
	EnchantedMelonBlock: 'ENCHANTED_MELON_BLOCK',
	EnchantedCactus: 'ENCHANTED_CACTUS',
	EnchantedCookie: 'ENCHANTED_COOKIE',
	EnchantedBrownMushroom: 'ENCHANTED_BROWN_MUSHROOM',
	EnchantedRedMushroom: 'ENCHANTED_RED_MUSHROOM',
	EnchantedRedMushroomBlock: 'ENCHANTED_HUGE_MUSHROOM_2',
	EnchantedBrownMushroomBlock: 'ENCHANTED_HUGE_MUSHROOM_1',
	EnchantedNetherWart: 'ENCHANTED_NETHER_STALK',
	MutantNetherWart: 'MUTANT_NETHER_STALK',

	JacobsTicket: 'JACOBS_TICKET',

	// Garden Chips
	CropshotChip: 'CROPSHOT_GARDEN_CHIP',
	VerminVaporizerChip: 'VERMIN_VAPORIZER_GARDEN_CHIP',
	SynthesisChip: 'SYNTHESIS_GARDEN_CHIP',
	SowledgeChip: 'SOWLEDGE_GARDEN_CHIP',
	MechamindChip: 'MECHAMIND_GARDEN_CHIP',
	HyperchargeChip: 'HYPERCHARGE_GARDEN_CHIP',
	EvergreenChip: 'EVERGREEN_GARDEN_CHIP',
	OverdriveChip: 'OVERDRIVE_GARDEN_CHIP',
	QuickdrawChip: 'QUICKDRAW_GARDEN_CHIP',
	RarefinderChip: 'RAREFINDER_GARDEN_CHIP',
} as const;
