import { REFORGE_SOURCES } from '../items/reforges/index.js';
import { Rarity, type Reforge } from './reforge-types.js';
import { Stat } from './stats.js';

export * from './reforge-types.js';

export const REFORGES: Record<string, Reforge> = REFORGE_SOURCES;

export const STAT_ICONS: Record<Stat, string> = {
	[Stat.Damage]: '❁',
	[Stat.FishingSpeed]: '☂',
	[Stat.CombatWisdom]: '☯',
	[Stat.TrophyChance]: '\uE02A',
	[Stat.TreasureChance]: '\uE025',
	[Stat.Tracking]: '\uE077',
	[Stat.Strength]: '❁',
	[Stat.Health]: '❤',
	[Stat.Defense]: '❈',
	[Stat.Speed]: '✦',
	[Stat.Intelligence]: '✎',
	[Stat.CritChance]: '☣',
	[Stat.CritDamage]: '☣',
	[Stat.AttackSpeed]: '⚔',
	[Stat.AbilityDamage]: '๑',
	[Stat.MagicFind]: '✯',
	[Stat.PetLuck]: '♣',
	[Stat.TrueDefense]: '❂',
	[Stat.SeaCreatureChance]: 'α',
	[Stat.Ferocity]: '⫽',
	[Stat.MiningSpeed]: '⸕',
	[Stat.MiningFortune]: '☘',
	[Stat.FarmingFortune]: '☘',
	[Stat.ForagingFortune]: '☘',
	[Stat.MiningWisdom]: '☯',
	[Stat.FarmingWisdom]: '☯',
	[Stat.ForagingWisdom]: '☯',
	[Stat.Pristine]: '✧',
	[Stat.BonusPestChance]: 'ൠ',
	[Stat.Overbloom]: '☀',
	[Stat.CactusFortune]: '☘',
	[Stat.CarrotFortune]: '☘',
	[Stat.CocoaBeanFortune]: '☘',
	[Stat.MelonFortune]: '☘',
	[Stat.MushroomFortune]: '☘',
	[Stat.NetherWartFortune]: '☘',
	[Stat.PotatoFortune]: '☘',
	[Stat.PumpkinFortune]: '☘',
	[Stat.SugarCaneFortune]: '☘',
	[Stat.WheatFortune]: '☘',
	[Stat.PestKillFortune]: '☘',
	[Stat.PestCooldownReduction]: 'ൠ',
	[Stat.SunflowerFortune]: '☘',
	[Stat.MoonflowerFortune]: '☘',
	[Stat.WildRoseFortune]: '☘',
};

/**
 * Stat glyphs for the Hypixel SkyBlock resource-pack font.
 * Requires that font to render the private-use Unicode characters.
 * @see https://hypixelskyblock.minecraft.wiki/w/Stats
 */
export const STAT_ICONS_UNICODE: Record<Stat, string> = {
	[Stat.Damage]: '\uE050',
	[Stat.Strength]: '\uE00D',
	[Stat.Health]: '\uE010',
	[Stat.Defense]: '\uE008',
	[Stat.Speed]: '\uE022',
	[Stat.Intelligence]: '\uE003',
	[Stat.CritChance]: '\uE02C',
	[Stat.CritDamage]: '\uE007',
	[Stat.AttackSpeed]: '\uE001',
	[Stat.AbilityDamage]: '\uE002',
	[Stat.MagicFind]: '\uE01A',
	[Stat.PetLuck]: '\uE013',
	[Stat.TrueDefense]: '\uE027',
	[Stat.SeaCreatureChance]: '\uE021',
	[Stat.Ferocity]: '\uE00B',
	[Stat.MiningSpeed]: '\uE015',
	[Stat.MiningFortune]: '\uE053',
	[Stat.FarmingFortune]: '\uE051',
	[Stat.CactusFortune]: '\uE051',
	[Stat.CarrotFortune]: '\uE051',
	[Stat.CocoaBeanFortune]: '\uE051',
	[Stat.MelonFortune]: '\uE051',
	[Stat.MushroomFortune]: '\uE051',
	[Stat.NetherWartFortune]: '\uE051',
	[Stat.PotatoFortune]: '\uE051',
	[Stat.PumpkinFortune]: '\uE051',
	[Stat.SugarCaneFortune]: '\uE051',
	[Stat.WheatFortune]: '\uE051',
	[Stat.SunflowerFortune]: '\uE051',
	[Stat.MoonflowerFortune]: '\uE051',
	[Stat.WildRoseFortune]: '\uE051',
	[Stat.PestKillFortune]: '\uE051',
	[Stat.PestCooldownReduction]: '\uE019',
	[Stat.ForagingFortune]: '\uE054',
	[Stat.MiningWisdom]: '\u262F',
	[Stat.FarmingWisdom]: '\u262F',
	[Stat.ForagingWisdom]: '\u262F',
	[Stat.Pristine]: '\uE01C',
	[Stat.BonusPestChance]: '\uE019',
	[Stat.Overbloom]: '\uE02B',
	[Stat.FishingSpeed]: '\uE00C',
	[Stat.CombatWisdom]: '\u262F',
	[Stat.TrophyChance]: '\uE02A',
	[Stat.TreasureChance]: '\uE025',
	[Stat.Tracking]: '\uE077',
};

export const RARITY_COLORS: Record<Rarity, string> = {
	[Rarity.Common]: '§f',
	[Rarity.Uncommon]: '§a',
	[Rarity.Rare]: '§9',
	[Rarity.Epic]: '§5',
	[Rarity.Legendary]: '§6',
	[Rarity.Mythic]: '§d',
	[Rarity.Divine]: '§b',
	[Rarity.Special]: '§c',
	[Rarity.VerySpecial]: '§c',
	[Rarity.Ultimate]: '§4',
	[Rarity.Admin]: '§4',
};
