/**
 * Generated by orval 🍺
 * Do not edit manually.
 * StreamAPI
 * OpenAPI spec version: v1
 */

export type GetLiveStreamsParams = {
	/**
	 * @nullable
	 */
	provider?: string | null;
	limit: number;
};
