/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * StreamAPI
 * OpenAPI spec version: v1
 */
import type { StreamAPIModelsStreamerProfileResponse } from './StreamAPIModelsStreamerProfileResponse';

export interface StreamAPIModelsStreamerDirectoryResponse {
	streamers?: StreamAPIModelsStreamerProfileResponse[];
}
