/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * StreamAPI
 * OpenAPI spec version: v1
 */
import type { StreamAPIModelsLiveStreamDto } from './StreamAPIModelsLiveStreamDto';

export interface StreamAPIModelsLiveStreamsResponse {
	streams?: StreamAPIModelsLiveStreamDto[];
}
