/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * StreamAPI
 * OpenAPI spec version: v1
 */
import type { StreamAPIModelsStreamerLinkDto } from './StreamAPIModelsStreamerLinkDto';

export interface StreamAPIModelsStreamerProfileDto {
	id?: bigint;
	/** @nullable */
	twitchUserId?: string | null;
	twitchLogin?: string;
	/** @nullable */
	twitchDisplayName?: string | null;
	/** @nullable */
	minecraftUuid?: string | null;
	/** @nullable */
	aboutMarkdown?: string | null;
	/** @nullable */
	priority?: number | null;
	/** @nullable */
	eliteCreatorCode?: string | null;
	/** @nullable */
	hypixelCreatorCode?: string | null;
	links?: StreamAPIModelsStreamerLinkDto[];
}
