/**
 * Generated by orval 🍺
 * Do not edit manually.
 * StreamAPI
 * OpenAPI spec version: v1
 */
import type { StreamAPIModelsStreamerProfileDto } from './StreamAPIModelsStreamerProfileDto';

export interface StreamAPIModelsLiveStreamDto {
	provider?: string;
	streamId?: string;
	providerUserId?: string;
	providerLogin?: string;
	providerDisplayName?: string;
	title?: string;
	url?: string;
	/** @nullable */
	thumbnailUrl?: string | null;
	viewerCount?: number;
	startedAt?: string;
	lastObservedAt?: string;
	matchedKeywords?: string[];
	streamer?: StreamAPIModelsStreamerProfileDto | null;
}
