import { Crop } from '../constants/crops.js';
import { FarmingToolType, type ItemDefinition } from './definitions.js';
import {
	CactusKnife1,
	CactusKnife2,
	CactusKnife3,
	CocoaChopper1,
	CocoaChopper2,
	CocoaChopper3,
	EclipseHoe1,
	EclipseHoe2,
	EclipseHoe3,
	EuclidsWheatHoe1,
	EuclidsWheatHoe2,
	EuclidsWheatHoe3,
	FungiCutter1,
	FungiCutter2,
	FungiCutter3,
	GaussCarrotHoe1,
	GaussCarrotHoe2,
	GaussCarrotHoe3,
	HoeOfNoTilling,
	MelonDicer1,
	MelonDicer2,
	MelonDicer3,
	NewtonNetherWartsHoe1,
	NewtonNetherWartsHoe2,
	NewtonNetherWartsHoe3,
	PumpkinDicer1,
	PumpkinDicer2,
	PumpkinDicer3,
	PythagoreanPotatoHoe1,
	PythagoreanPotatoHoe2,
	PythagoreanPotatoHoe3,
	TuringSugarCaneHoe1,
	TuringSugarCaneHoe2,
	TuringSugarCaneHoe3,
	WildRoseHoe1,
	WildRoseHoe2,
	WildRoseHoe3,
} from './tools/index.js';

export { FarmingToolType, type ItemDefinition as FarmingToolInfo };

type FarmingToolInfo = ItemDefinition;

export const FARMING_TOOLS: Partial<Record<string, FarmingToolInfo>> = {
	CACTUS_KNIFE: new CactusKnife1(),
	CACTUS_KNIFE_2: new CactusKnife2(),
	CACTUS_KNIFE_3: new CactusKnife3(),
	COCO_CHOPPER: new CocoaChopper1(),
	COCO_CHOPPER_2: new CocoaChopper2(),
	COCO_CHOPPER_3: new CocoaChopper3(),
	FUNGI_CUTTER: new FungiCutter1(),
	FUNGI_CUTTER_2: new FungiCutter2(),
	FUNGI_CUTTER_3: new FungiCutter3(),
	MELON_DICER: new MelonDicer1(),
	MELON_DICER_2: new MelonDicer2(),
	MELON_DICER_3: new MelonDicer3(),
	PUMPKIN_DICER: new PumpkinDicer1(),
	PUMPKIN_DICER_2: new PumpkinDicer2(),
	PUMPKIN_DICER_3: new PumpkinDicer3(),
	THEORETICAL_HOE_CARROT_1: new GaussCarrotHoe1(),
	THEORETICAL_HOE_CARROT_2: new GaussCarrotHoe2(),
	THEORETICAL_HOE_CARROT_3: new GaussCarrotHoe3(),
	THEORETICAL_HOE_WARTS_1: new NewtonNetherWartsHoe1(),
	THEORETICAL_HOE_WARTS_2: new NewtonNetherWartsHoe2(),
	THEORETICAL_HOE_WARTS_3: new NewtonNetherWartsHoe3(),
	THEORETICAL_HOE_POTATO_1: new PythagoreanPotatoHoe1(),
	THEORETICAL_HOE_POTATO_2: new PythagoreanPotatoHoe2(),
	THEORETICAL_HOE_POTATO_3: new PythagoreanPotatoHoe3(),
	THEORETICAL_HOE_CANE_1: new TuringSugarCaneHoe1(),
	THEORETICAL_HOE_CANE_2: new TuringSugarCaneHoe2(),
	THEORETICAL_HOE_CANE_3: new TuringSugarCaneHoe3(),
	THEORETICAL_HOE_WHEAT_1: new EuclidsWheatHoe1(),
	THEORETICAL_HOE_WHEAT_2: new EuclidsWheatHoe2(),
	THEORETICAL_HOE_WHEAT_3: new EuclidsWheatHoe3(),
	THEORETICAL_HOE_SUNFLOWER_1: new EclipseHoe1(),
	THEORETICAL_HOE_SUNFLOWER_2: new EclipseHoe2(),
	THEORETICAL_HOE_SUNFLOWER_3: new EclipseHoe3(),
	THEORETICAL_HOE_WILD_ROSE_1: new WildRoseHoe1(),
	THEORETICAL_HOE_WILD_ROSE_2: new WildRoseHoe2(),
	THEORETICAL_HOE_WILD_ROSE_3: new WildRoseHoe3(),
	HOE_OF_NO_TILLING: new HoeOfNoTilling(),
};

export const BEST_FARMING_TOOLS: Partial<Record<Crop, FarmingToolInfo>> = {
	[Crop.Cactus]: FARMING_TOOLS.CACTUS_KNIFE_3 ?? FARMING_TOOLS.CACTUS_KNIFE,
	[Crop.CocoaBeans]: FARMING_TOOLS.COCO_CHOPPER_3 ?? FARMING_TOOLS.COCO_CHOPPER,
	[Crop.Mushroom]: FARMING_TOOLS.FUNGI_CUTTER_3 ?? FARMING_TOOLS.FUNGI_CUTTER,
	[Crop.Melon]: FARMING_TOOLS.MELON_DICER_3,
	[Crop.Pumpkin]: FARMING_TOOLS.PUMPKIN_DICER_3,
	[Crop.Carrot]: FARMING_TOOLS.THEORETICAL_HOE_CARROT_3,
	[Crop.NetherWart]: FARMING_TOOLS.THEORETICAL_HOE_WARTS_3,
	[Crop.Potato]: FARMING_TOOLS.THEORETICAL_HOE_POTATO_3,
	[Crop.SugarCane]: FARMING_TOOLS.THEORETICAL_HOE_CANE_3,
	[Crop.Wheat]: FARMING_TOOLS.THEORETICAL_HOE_WHEAT_3,
};
