name: Svelte Check

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
  # Set below
  STORE_PATH: ''

jobs:
  check:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpm run check