name: Website

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Lint
              run: pnpm run lint
    check:
        name: Svelte Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Check
              run: pnpm run check
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Build
              run: pnpm run build
